### PR TITLE
Issue 13 - PH5 StationTXT is missing some information

### PR DESCRIPTION
**Pull request by nick-iris**
This pull request is enable future discussion and peer reviews/testing for issue 13 changes.

### CODE REVIEW

**Comment by nick-iris** [comment]
@derick-hess Lets continue to work on #13 on this branch, since there will be additional performance improvements made and we want to keep _master_ stable.

**Comment by nick-iris** [comment]
I've started working on adding a method in ph5API to read the first entry of a das table for any given das. The idea is that this will allow us to read the _azimuth_ and _dip_ without reading an arbitrary range of data.

This is what I have so far. Does this seem right?

```
    def read_first_das_t(self, das):
        das_g = "Das_g_{0}".format (das)
        if self.Das_g_names == [] : 
            self.read_das_g_names ()
        if das_g in self.Das_g_names :
            node = self.ph5_g_receivers.getdas_g (das)
            self.ph5_g_receivers.setcurrent (node)
        if not self.Das_t_full.has_key (das) :
            rows, keys = self.ph5_g_receivers.read_das ()
            self.Das_t_full[das] = { 'rows':rows, 'keys':keys }
        self.Das_t[das] = self.Das_t_full[das]
```

**Comment by nick-iris** [comment]
Is the optimization to read only the first das even necessary? The following seems to work fine:

```
        self.ph5.read_das_t(das)
        if self.ph5.Das_t.has_key(das):
            Das_t = ph5API.filter_das_t(self.ph5.Das_t[das]['rows'],
                                        station_list[deployment][0][
                                            'channel_number_i'])
            Receiver_t=self.ph5.get_receiver_t (Das_t[0], by_n_i=True)
            obs_channel.azimuth=Receiver_t['orientation/azimuth/value_f']
            obs_channel.dip=Receiver_t['orientation/dip/value_f']
```

**Comment by rsdeazevedo** [comment]
Nick;

You need to be careful. It is possible that the DAS was at several 
different stations with several differing sensor orientations over the 
experiment. You will need to read appropriate Array_t to find out the 
time period that the DAS was at a station and get the appropriate 
Receiver_t entry. A common way to orient sensors on controlled source 
experiments is to orient one of the components along and one across 
line, so, it is possible for the azimuth and dip to be time dependent 
for a given DAS.

steve.

**Comment by nick-iris** [comment]
Thanks @rsdeazevedo  that makes sense.

Would providing the channel start and end times when calling ph5.read_das_t accomplish this?
i.e.
```
   channel_start = station_list[deployment][0]['deploy_time/epoch_l']
   channel_end = station_list[deployment][0]['pickup_time/epoch_l']
   self.ph5.read_das_t(das, channel_start, channel_end)
   Das_t = ph5API.filter_das_t(self.ph5.Das_t[das]['rows'],
                                  station_list[deployment][0]['channel_number_i'])
```
Basically we just need to read the correct azimuth and dip for a given das.

**Comment by rsdeazevedo** [comment]
Yes.

**Comment by nick-iris** [comment]
@rsdeazevedo Can you please review these changes?

If they look okay I'll rebase on top of master and do a squash merge.

**Comment by nick-iris** [comment]
@derick-hess could also do the review.

**Comment by derick-hess** [comment]
I'll take a look at it this weekend and review it

**Comment by nick-iris** [comment]
Thanks. Assuming that this change will work, then we have all the pieces of information to create complete channel level StationTXT.

I just pushed an update (https://github.com/PIC-IRIS/PH5/pull/36/commits/47e4a7b2408c1f8cc83a72e7edd261bd88585a5a) on the fix_11 branch to make sure Scale, ScaleFreq, and ScaleUnits are also included.

**Pull request merged**
