### PR TITLE
SEG-Y output in web services

### PR DESCRIPTION
**Pull request by nick-iris**
### What does this PR do?
Additional metadata for a SEG-Y timeseries output was added to the trace objects returned by `ph5toms`. This information is used by the web services to write SEG-Y.

I have a modified version of the segyfactory.py code that I am using to write SEG-Y in the web services. If desired we could add that code to PH5 so that the `ph5toms` command can also write SEG-Y.

### Please note
I think it would be best to merge the `availability` branch before this branch.

### CODE REVIEW

**Comment by nick-iris** [comment]
Once we merge the `availability` branch I'll rebase this onto master. At that point this will be deployed to the ph5wsbeta web services. I'd like for PASSCAL to help validate the SEG-Y data that the web services create, since you are the experts in that area.

**Comment by derick-hess** [comment]
I'll get a working group together at PASSCAL to test out the beta SEG-Y service and validate output.

**Comment by nick-iris** [comment]
Rebased [current master](https://github.com/PIC-IRIS/PH5/commit/44b31c41c24daae53cc01a046559c4138d7fe4a2) and force updated.

**Comment by nick-iris** [comment]
Not much to review here. I had to do a bit of refactoring and added some metadata fields to the Trace objects for writing SEG-Y data via the web services.

**Comment by nick-iris** [comment]
@dsentinel and @derick-hess. I really need to get this merged to get the web services to a stable state. The changes are minor and shouldn't affect the command line clients.

**Pull request merged**
