### PR TITLE
Minor Fixes

### PR DESCRIPTION
**Pull request by derick-hess**
ph5.core.ph5utils
   doy_breakup can now accept vairable time lengths for breakup. Default is 1 day

ph5.clients.ph5tostationxml
   fixed array number bug

ph5.clients.ph5toms
   fixed array number bug
   added LENGTH global variable to adjust file cuts

### CODE REVIEW

**Comment by derick-hess** [comment]
The LENGTH variable allows for tuning and setting the cut length in ph5toms.  This makes it much easier for me to compare the web service results with the command line results since I can make the traces look the same. PQl doesnt combine each individual day.ms file into one trace per channel.

I have also found that tuning the cut length can speed up ph5toms. Since webservice out put just appends everything on the same channel into one trace the actual cut length doesn't matter since it will always look the same on the output.

This will hopefully help us fine tune the speed of ph5toms on the webservices

**Comment by derick-hess** [comment]
the ph5api does try to filter the das_t every time even if it doesn't read it. Sending it the already filtered das_t ph5toms creates gives a small speedup

**Comment by nick-iris** [comment]
Can you update the change log since most of the changes were yours?

**Comment by derick-hess** [comment]
Yeah I'll update the changelog now

**Pull request merged**
