### PR TITLE
fix #81

### LINKED ISSUE #81: PH5toStationXML Response Management
We need to add a key for sample rate. Since there are different responses based on sample rate that can have the same sensor_key and data_logger key, another ket based on sample_rate needs to be added.

I found this when the VM stations were added. There is now response for VM currently in the PH5, but I noticed since they are still cmg-3t/rt130 instruments, it's using the last loaded response and loading that into the inventory object as the response for the VM channels.

I think this error would only ever come up if there is no response for a channel and it matched keys from a previous channel.

### PR DESCRIPTION
**Pull request by derick-hess**
Adds sample rate as a key in for data_logger in the response manager and updates site name to contain the description

### CODE REVIEW

**Comment by derick-hess** [comment]
I think all you will need to do in your stationtxt code is use sensor.description instead of sensor.type to get the correct description. I couldn't find a better place to stick the combined description in the obspy channel. 

I think this way will work out without altering the stationxml sensor type description while sill allowing for the combined description in stationtxt

**Comment by nick-iris** [comment]
Looks good in the StationXML, but I'm only seeing the sensor type for the StationTxt SensorDescription.

It looks like the ObsPy code I added is using SensorType. I'll have to look into updating that:
https://github.com/obspy/obspy/pull/1466/files#diff-b4a110458209fcf13fc8aa4eb4237bc9R367

In the mean time, I'll use a local version for writing StationTxt.

**Comment by nick-iris** [comment]
I went ahead and updated Web Services on the server to include these fixes. The local method we are using to write StationTxt to use the sensor description. I'll work with ObsPy to get that copy updated as well. Thanks for making these changes.

Is there anything else left to be done on the Wavefields experiment?

**Comment by derick-hess** [comment]
I think everything is done on wavefields but I'll spend this afternoon giving the metadata from fdsn web services vs ph5 a look over to see if there is anything missing just to make sure.

**Comment by nick-iris** [comment]
Thanks I appreciate you also looking it over in case I missed something. We'll then want to use the notes in the google doc to create a final list of differences to send to the directors in order to get their final approval.

**Pull request merged**
