### PR TITLE
Fix for error when requesting multiple days

### PR DESCRIPTION
**Pull request by derick-hess**
Fixes an error when requesting multiple days worth of data. Error was caused by int being returned instead of a float.

### CODE REVIEW

**Comment by derick-hess** [comment]
Need to fix a bit more on this, found another place that needs changing

**Comment by nick-iris** [comment]
Okay no problem. Let me know when you're ready to merge the changes.

**Comment by derick-hess** [comment]
Okay should be good to test

**Comment by nick-iris** [comment]
I just pulled this down and deployed to the ph5beta endpoint. The service still returns data. What issue was this fixing exactly?

**Comment by derick-hess** [comment]
It happened during the breakup of multiple days. SO if you made a request that spanned multiple days say 

https://service.iris.edu/ph5beta/dataselect/1/query?network=YW&station=1001,2019,518,601&starttime=2016-06-24T00:00:00&endtime=2016-06-29T01:00:00&nodata=404

It would report an error not knowing what to do with an extra .000  because doy_breakup was getting an int instead of a float and would exit.

I also made sure everywhere  passcal2epoch was called returned a floating point epoch.

**Pull request merged**
