### PR TITLE
Helpfile

### PR DESCRIPTION
**Pull request by dthomas1953**
Thank your for contributing to PH5

Before submitting a PR, please review the pull request guidelines:
https://github.com/PIC-IRIS/PH5/blob/master/CONTRIBUTING.md#submitting-a-pull-request

### What does this PR do?
Adds a general help file, ph5.py, to the utilities folder. Executing without arguments displays a list of all utilities and programs for which info is available. Executing with an argument, such as pforma, displays information about that utility.

### Relevant Issues?
I did not update/ add a link to ph5.py in setup.py, as this is tricksy.
 
###Checklist
- [X] This PR is not directly related to an existing issue (which has no PR yet).
- [X] All tests pass.
- [X] Any new or changed features have are documented.
- [X] Changes have been added to `CHANGELOG.txt` .
- [X] First time contributors have added your name to `CONTRIBUTORS.txt` .

### CODE REVIEW

**Comment by derick-hess** [comment]
Going to make a few minor additions and update setup.py. I'll need to rename this from ph5.py to ph5_help.py because of import issues, but the command will still be called ph5

**Comment by derick-hess** [comment]
closes #192

**Comment by nick-iris** [comment]
`ph5_help.py` quickly becomes out of sync with the actual ph5 commands since it is hardcoded. I think it should be updated to dynamically get the help documentation from the console script source code.

**Comment by dthomas1953** [comment]
Sounds like a good plan. In the meanwhile, I'll try to update this periodically.

**Comment by nick-iris** [comment]
I think this should be simplified before a new version of PH5 is released. IMO, when a user types `ph5` then a list of available commands should displayed along with a short description for each.  For example:
```
| => ph5
PH5: PASSCAL HDF5

Usage:
  <command> [args]

Client Commands:
  ph5toms           |  Extract MSEED or SAC from a family of ph5 files.
  ph5tostationxml   |  Extract station meta-data in StationXML, Text, or KML formats.
  ph5toevt          |  Extract event meta-data in Quakeml or EML.
  ph5torec          |  Extract SEG-Y from a family of ph5 files in receiver order.
  ph5toexml         |  Extract SEG-Y from a family of ph5 files in shot order.

Data and Metadata QC Commands:
  ph5tokef          |  Dump select tables from a family of ph5 files to a KEF file. Can also be used to edit table data.
  keftocsv          |  Convert a KEF file to CSV.
  csvtokef          |  Convert a CSV file to KEF.

... etc. for all commands

Type "<command> --help" for more information on a command.
```
You could just define a class containing each command name, description, and entry point (e.g. `ph5.utilities.125a2ph5:main`). This could then dynamically get used to define the list of commands in the `setup.py` definition and in the help message.

**Pull request merged**
