### PR TITLE
2017.242, Standardized GUI and command line program names.

### PR DESCRIPTION
**Pull request by rsdeazevedo**

### CODE REVIEW

**Comment by nick-iris** [comment]
I think this is fine to merge but maybe we should wait to add some more features before publishing another release. Your call.

**Comment by derick-hess** [comment]
Yeah I have some enhancements to help info on ph5toms and other stuff will come up I'm sure. We can merge this then wait until we have at least 4-5 changes to do another release.

**Comment by derick-hess** [comment]
I'm going to update the changelog for this before merging

**Comment by rsdeazevedo** [comment]
How does a squash merge work if we all have a bunch of small changes?

**Comment by derick-hess** [comment]
squash merge will take all the small commits from this PR and commit them as a single commit into the master

**Pull request merged**
