### PR TITLE
Raise an exception if no PH5 experiments are found under the supplied basepath.

### PR DESCRIPTION
**Pull request by nick-iris**
I added a check to make sure that PH5 experiments exists under the given PH5 basepath.

### CODE REVIEW

**Comment by nick-iris** [comment]
I just added am additional change where I modified ph5tostationxml.py and ph5toexml.py to use the multiprocessing ThreadPool instead of Pool.

**Comment by nick-iris** [comment]
Actually I'm going to switch this PR back to not include the ThreadPool change. After running some tests on the server, I've concluded that running multiple processes is much faster in this case.

**Comment by derick-hess** [comment]
okay sounds good. Testing now

**Comment by nick-iris** [comment]
Cool. I'll squash and merge.

**Pull request merged**
