### PR TITLE
Remove sys.exit() #215 and global variables #218

### PR DESCRIPTION
**Pull request by damhuonglan**
+ #125 sys.exit()s have been removed for most of files except for the ones in __main__ and GUI exit
+ #218 global variables have been removed (change to class in most of the cases)
+ correct closeEvent for kefedit.py and ph5_viewer.py
+ correct bug caused by auto flake8 before in ph5_viewer's creating SEGY for shot gather

### CODE REVIEW

**Comment by derick-hess** [comment]
pyflakes fails:
 ph5/utilities/report_gen.py:565: undefined name 'read_das_groups'

**Comment by derick-hess** [comment]
@damhuonglan I'll give this check over the next few days. Some things might need to be changed in 125a2ph5 and 1302ph5, but it should be minor. pforma looks for certain keywords in the output form these programs to know if processing is finished so the output has to be exactly like it was before. 

I'll make sure these work.

**Comment by derick-hess** [comment]
@damhuonglan there are a few flake8 errors still

**Comment by damhuonglan** [comment]
@derick-hess I have run `flake8 --filename *.py` for utilities/, core/, client/ and there is no flake8 issue left. The flake8 issues can be found is in setup.py but I didn't do anything with that file. Should I solve the flake8 issues for setup.py or not? If the issues are in other files, can you show me the list of flake8 issues that you found please?

**Comment by derick-hess** [comment]
these are the errors that happend after the last commit: Merge branch 'master' into remove_sys_exit

ph5/utilities/dumpfair.py:135:1: E303 too many blank lines (3)
ph5/utilities/seg2toph5.py:563:9: F821 undefined name 'update_external_references'

**Comment by derick-hess** [comment]
you can also view them here https://travis-ci.org/PIC-IRIS/PH5/builds/502199304?utm_source=github_status&utm_medium=notification

**Comment by derick-hess** [comment]
make sure you pull the changes to your local machine if you fixed the merge issues from the browser.

**Comment by derick-hess** [comment]
@damhuonglan I'm looking at ph5toms. SPecifically 16 days ago in one for your merges you did this. https://github.com/PIC-IRIS/PH5/commit/729fbdb2f2a6a2142da804a84d2d2ab012921477#diff-f3afc418803b1a3307667be10e659ff9

It looks like you took out all the changes you made to ph5toms. In this commit you removed all the changes you added for inday breakup as well as any changes you made to removing global variables.

**Comment by derick-hess** [comment]
@damhuonglan running the tests it also looks like segdtoph5 is now broken. I tno longer writes correct values into the data arrays. It writes the value -2147483648 into many entries.

**Comment by derick-hess** [comment]
realized that when I created the fake fcnt files the random generated data had some values that are too large, so ph5toms will throw an error trying to pack the data. I will fix the fcnt file when I write the segdtoph5 unit tests. The current fcnt works fine for for testing most things as they don't actually care what the data is, just that it matches what is expected so it will work for now.

**Comment by damhuonglan** [comment]
@derick-hess I already reverted the branch to commit 450feac. I will ask somebody to review on this. But I think you already check most of files. Please verify the files you have checked. Thank you.

**Comment by damhuonglan** [comment]
@nick-iris In this branch I have removed sys.exit() and global variables in files. I want to merge this file to master to make it easier when writing unit tests. All checks have passed. This branch still need reviews to be merged. Could you please help to review the files in this branch, at least review your contribution in master? Thank you.

**Comment by damhuonglan** [comment]
@dsentinel This is the conversation for merging remove_sys_exit

**Comment by damhuonglan** [comment]
Please check the package that you have been reviewed.
Clients
- [ ] ph5availability
- [ ] ph5toevt
- [ ] ph5torec
- [ ] ph5toexml
- [ ] ph5toms
- [ ] ph5tostationxml

Core
- [ ] columns
- [ ] cs2cs
- [ ] decimate
- [ ] ebcdic
- [ ] experiment
- [ ] external_file
- [ ] ibmfloat
- [ ] kef
- [ ] kefutility
- [ ] kefx
- [ ] mplturkey
- [ ] ph5api
- [ ] ph5utils
- [ ] pmonitor
- [ ] pn125
- [ ] pn130
- [ ] rt_130_h
- [ ] sac_h (maybe obsolete and need removal)
- [ ] sacfactory (maybe obsolete and need removal)
- [ ] sacreader (maybe obsolete and need removal)
- [ ] segd_h
- [ ] segdreader
- [ ] segy_h
- [ ] segyfactory
- [ ] segyreader
- [ ] sfactory
- [ ] timedoy

Utilities
- [ ] 125a2ph5
- [ ] 1302ph5
- [ ] changes
- [ ] cross_check_event_array_data
- [ ] csvtokef
- [ ] dumpfair
- [ ] dumpsac (Needs rewrite...use Obspy)
- [ ] dumpsgy
- [ ] fix_3chan_texan
- [ ] fix_num_samples
- [ ] geod2kef
- [ ] grao2ph5 (obsolete...remove)
- [ ] index_offset_t
- [ ] initialize_ph5
- [ ] kef2kml
- [ ] kef2ph5
- [ ] kefedit
- [ ] keftocsv
- [ ] load_das_t
- [ ] meta_data_gen
- [ ] metadatatoph5
- [ ] noven
- [ ] novenkef
- [ ] novenqc
- [ ] novitiate (might be obsolete)
- [ ] nuke_tables
- [ ] obspytoph5
- [ ] pforma_io
- [ ] pformacl
- [ ] pformagui
- [ ] ph5_help
- [ ] ph5_merge_helper
- [ ] ph5_total
- [ ] ph5validate
- [ ] segd_h
- [ ] recreate_external_references
- [ ] report2ph5
- [ ] report_gen
- [ ] resp_load
- [ ] seg2toph5
- [ ] segd2ph5
- [ ] segy2ph5
- [ ] set_deploy_pickup_times
- [ ] set_n_i_response
- [ ] sort_array_t
- [ ] sort_kef_gen
- [ ] tabletokef
- [ ] time_kef_gen
- [ ] unsimpleton
- [ ] watchit

**Comment by nick-iris** [comment]
I can help review it. On my end of things I can mostly check that things still work well with the PH5 web services. These services use the `ph5toms`, `ph5availability`, `ph5tostationxml`, and `ph5toexml` clients, as well as, the `ph5api`. I think someone at PASSCAL should help testing the other PH5 utilities that that the PI's would use.

**Comment by damhuonglan** [comment]
@ascire-pic Please you comment the files you have tested here. Thank you.

**Comment by nick-iris** [comment]
@dsentinel The web services still work after these changes, so feel free to merge if you're happy with everything

**Comment by damhuonglan** [comment]
Too big too much. Will chop off into small trunks to merge.

**Pull request closed without merging**
