### PR TITLE
I393 mstoph5 - add option --from_mini

### PR DESCRIPTION
**Pull request by damhuonglan**
What does this PR do?

In issue #393, Alissa commented to request to add the similar argument like PR426 in mstoph5.

This PR adds option -F from_mini to continue index for mini file from, in which the mini files created will not be greater than 100GB. This option will not be associated with option -M num_mini.

The help in segdtoph5 is modified and added example as following to avoid misleading:

  -M num_mini, --num_mini=num_mini
                        Create a given number of miniPH5 files. Ex: -M 38
  -S first_mini, --first_mini=first_mini
                        The index of the first miniPH5_xxxxx.ph5 file of all.
                        Ex: -S 5
  -F from_mini, --from_mini=from_mini
                        The index to continue miniPH5_xxxxx.ph5 file from. Do
                        not associate with option -M. Ex: -F 25

### Checklist
- [ ] This PR is not directly related to an existing issue (which has no PR yet).
- [ ] All tests pass.
- [ ] Any new or changed features have are documented.
- [ ] Changes have been added to `CHANGELOG.txt` .
- [ ] First time contributors have added your name to `CONTRIBUTORS.txt` .

### CODE REVIEW

**Comment by hrotman-pic** [comment]
I would like to request changes to make the optional flags consistent with the flags used in the other ingestion commands (segdtoph5, 125atoph5, 130toph5, seg2toph5).

-r raw_file to use for adding one miniseed file (currently -f)

-f file_list_file to use a file containing a list of of miniseed files to add (currently -l)

**Review by hrotman-pic — CHANGES_REQUESTED** [review]
Based on the discussion yesterday, I am requesting:
Removal of -F option, so that users cannot recreate the problem of data from one DAS in two or more mini files.

The changes to the help for other options, such as 'Ex: -M 38' are still useful in my view.

I am not sure about keeping 'Recommend using when creating a new PH5' for the -M option help (for all ingestion commands in this PR). If we keep it, I think it will help if the help for the -M option also says that adding new data to an existing PH5 may not create new mini files.

Going slightly out of the scope of the discussion:
I think it would also help to state that -S defaults to 1 if not specified in the help for -S option.
I would also like to request the flags for a file and file list be changed so they are consistent with the flags used in the other ingestion commands (segdtoph5, 125atoph5, 130toph5, seg2toph5).

-r raw_file to use for adding one miniseed file (currently -f)

-f file_list_file to use a file containing a list of of miniseed files to add (currently -l)

**Comment by damhuonglan** [comment]
> I am not sure about keeping 'Recommend using when creating a new PH5' for the -M option help (for all ingestion commands in this PR). If we keep it, I think it will help if the help for the -M option also says that adding new data to an existing PH5 may not create new mini files.

I don't think we should keep 'Recommend using when creating a new PH5'. This is only reasonable if we have the flag F. Because this flag works for all cases. I will add explanation for all data ingestion command that data of a data will be kept in one minifile only. You will correct me when you test the PR.
I will create a new branch and a new PR for these changes. I want to keep this branch to look back in need.

**Comment by damhuonglan** [comment]
replaced with PR#434

**Pull request closed without merging**
