### PR TITLE
Change pforma_io so that pforma works with SmartSolo SEGD

### PR DESCRIPTION
**Pull request by damhuonglan**
### What does this PR do?
Solving issue #472 by adding regex for smartsolo and let pforma recognize it as FairField nodal to call segd2ph5 for SmartSolo Segd

### Checklist
- [ ] This PR is not directly related to an existing issue (which has no PR yet).
- [x] All tests pass.
- [ ] Any new or changed features have are documented.
- [ ] Changes have been added to `CHANGELOG.txt` .
- [ ] First time contributors have added your name to `CONTRIBUTORS.txt` .

### CODE REVIEW

**Comment by hrotman-pic** [comment]
I used this to make a fairly large PH5, with ~19100 total files from ~200 SmartSolos.  I have not run into any errors or problems with the PH5.  The mini files in the Sigma directory do not have continuous numbering, for example the first several minis are named:
miniPH5_00001.ph5
miniPH5_00002.ph5
miniPH5_00003.ph5
miniPH5_00004.ph5
miniPH5_00005.ph5
miniPH5_00011.ph5
miniPH5_00012.ph5
miniPH5_00013.ph5
miniPH5_00014.ph5
miniPH5_00021.ph5
miniPH5_00022.ph5
miniPH5_00023.ph5
miniPH5_00024.ph5

I think the discontinuous numbering mini files happens sometimes with Fairfield data, so I think it is not a problem?

As far as I've seen, each mini file has data from one DAS and most of the mini files are between 14-18 GB each.

**Review by ascire-pic — APPROVED** [review]
Tested the PR with both a Smartsolo-only data set as well as a joint SmartSolo/Fairfield data set. pforma runs without error and creates a valid PH5 archive containing all data. Looks good to me.

**Review by ascire-pic — APPROVED** [review]
Tested with SmartSolo only data set and mixed SmartSolo Fairfield data set. Resulting PH5s for both tests look good.

**Review by timronan — APPROVED** [review]
All of these changes look good. Thanks for including the test case.

**Pull request merged**
