### PR TITLE
Fix 460: Truncates PH5 availability at the deploy and pickup times

### PR DESCRIPTION
**Pull request by timronan**
Thank your for contributing to PH5

Before submitting a PR, please review the pull request guidelines:
https://github.com/PIC-IRIS/PH5/blob/master/CONTRIBUTING.md#submitting-a-pull-request

### What does this PR do?
Truncates PH5 availability at the deploy and pickup times. This PR prevent PH5 availability from displaying data that falls outside of the metadata epochs. The purpose of this PR is to make the output from ph5toms match the output of PH5 availability when there are data that fall outside of the deploy or pickup times. The timeseries data that fall outside of the metadata epoch are caught by ph5_validate so we will not loose a record of them.

### Relevant Issues?
Issue #460

### Checklist
- [ ] This PR is not directly related to an existing issue (which has no PR yet).
- [ ] All tests pass.
- [ ] Any new or changed features have are documented.
- [ ] Changes have been added to `CHANGELOG.txt` .
- [ ] First time contributors have added your name to `CONTRIBUTORS.txt` .

### CODE REVIEW

**Review by hrotman-pic — CHANGES_REQUESTED** [review]
Hi Tim, thanks for making these updates.  I can see the changes in the logic and think this PR is heading the right direction.

PH5s with multiple deployments are unfortunately showing some confusing or inaccurate output.

Confusing output is associated with Fairfield node PH5s with multiple deploy-pickup epochs.  The availability output is repeated--if there are 4 deploy-pickup epochs, the same availability lines prints 4 times for each SNCL.  I am not sure what is causing this (as far as I can tell, PH5WS availability does not print with availability output lines repeated).  If you want some examples, I can post in a separate comment or email them to you.

If data extends after pickup time (spotted with multiple deployments, also occurs with one deployment), it looks like latest availability is rounded down to the whole second.  Do we want to round?  Example from 19-024 (validated, archived) for one channel:
ph5availability -n master.ph5 -p . --station 1110 -S -a 2 -f t
`1B 1110  -- GP1        1000.0 2019-08-07T23:24:58.996000Z 2019-08-19T18:30:25.000000Z`
Array table lines for pickup time:
`pickup_time/ascii_s=Mon Aug 19 18:30:25 2019`
`pickup_time/micro_seconds_i=236999`

For Fairfield node PH5s with multiple deploy-pickup epochs, the earliest for the first epoch and the latest for the last epoch look like they go with what is in the array table, though latest for last epoch does is whole second.  Earliest is slightly later, which I think is OK and expected since it takes a few minutes for the node to turn on and get a GPS lock and start recording. 

For Fairfield node PH5s with multiple deploy-pickup epochs, the epochs that are not the last epoch print availability with latest a bit after the pickup time in the array table.  Earliest is shortly after deploy time in the array table and looks fine to me.  Examples from 18-027 (validated, archived) for one channel of one station:
ph5availability -n master.ph5 -p . --station 1101 -S -a 2 -f t
`2B 1101  -- DP1         500.0 2018-01-17T23:08:57.851999Z 2018-01-26T16:38:57.851999Z`
Pickup in array table for this epoch: `pickup_time/ascii_s=Fri Jan 26 16:12:38 2018`
`2B 1101  -- DP1         500.0 2018-01-26T16:59:35.048000Z 2018-03-01T03:59:35.048000Z`
Pickup in array table for this epoch: `pickup_time/ascii_s=Thu Mar  1 03:44:57 2018`
`2B 1101  -- DP1         500.0 2018-03-02T18:13:56.931998Z 2018-03-27T14:43:56.931998Z`
Pickup in array table for this epoch: `pickup_time/ascii_s=Tue Mar 27 14:27:00 2018`

For Texan experiments where a given Texan S/N was deployed at more than one station, I'll provide an example from 15-027 (validated and archived) for Texan S/N 12394, which was deployed at station 1007 from 2015-11-09T00:00:00 to 2015-11-19T00:00:00, and then deployed at station 3017 from 2015-11-21T23:30:00 to 2015-11-27T09:30:00.  I've picked an example from 15-027 because it had a few recording windows at each station, even though this leads to a longer example.  Behavior 
ph5availability -n master.ph5 -p . --station 1007 -S -a 2 -f t
`#n s     l  c   q sample-rate                    earliest                      latest`
`3B 1007  -- DPZ         250.0 2015-11-10T00:30:00.000000Z 2015-11-10T10:30:00.000000Z`
`3B 1007  -- DPZ         250.0 2015-11-11T00:30:00.000000Z 2015-11-11T10:30:00.000000Z`
`3B 1007  -- DPZ         250.0 2015-11-12T00:30:00.000000Z 2015-11-12T10:30:00.000000Z`
`3B 1007  -- DPZ         250.0 2015-11-13T00:30:00.000000Z 2015-11-13T10:30:00.000000Z`
`3B 1007  -- DPZ         250.0 2015-11-14T00:30:00.000000Z 2015-11-14T10:30:00.000000Z`
`3B 1007  -- DPZ         250.0 2015-11-15T00:30:00.000000Z 2015-11-15T10:30:00.000000Z`
`3B 1007  -- DPZ         250.0 2015-11-16T00:30:00.000000Z 2015-11-16T10:30:00.000000Z`
`3B 1007  -- DPZ         250.0 2015-11-17T00:30:00.000000Z 2015-11-17T10:30:00.000000Z`
`3B 1007  -- DPZ         250.0 2015-11-21T23:30:00.000000Z 2015-11-19T00:00:00.000000Z`
`3B 1007  -- DPZ         250.0 2015-11-22T23:30:00.000000Z 2015-11-19T00:00:00.000000Z`
`3B 1007  -- DPZ         250.0 2015-11-23T23:30:00.000000Z 2015-11-19T00:00:00.000000Z`
`3B 1007  -- DPZ         250.0 2015-11-24T23:30:00.000000Z 2015-11-19T00:00:00.000000Z`
`3B 1007  -- DPZ         250.0 2015-11-25T23:30:00.000000Z 2015-11-19T00:00:00.000000Z`
`3B 1007  -- DPZ         250.0 2015-11-26T23:30:00.000000Z 2015-11-19T00:00:00.000000Z`

ph5availability -n master.ph5 -p . --station 3017 -S -a 2 -f t
`#n s     l  c   q sample-rate                    earliest                      latest`
`3B 3017  -- DPZ         250.0 2015-11-10T00:30:00.000000Z 2015-11-10T10:30:00.000000Z`
`3B 3017  -- DPZ         250.0 2015-11-11T00:30:00.000000Z 2015-11-11T10:30:00.000000Z`
`3B 3017  -- DPZ         250.0 2015-11-12T00:30:00.000000Z 2015-11-12T10:30:00.000000Z`
`3B 3017  -- DPZ         250.0 2015-11-13T00:30:00.000000Z 2015-11-13T10:30:00.000000Z`
`3B 3017  -- DPZ         250.0 2015-11-14T00:30:00.000000Z 2015-11-14T10:30:00.000000Z`
`3B 3017  -- DPZ         250.0 2015-11-15T00:30:00.000000Z 2015-11-15T10:30:00.000000Z`
`3B 3017  -- DPZ         250.0 2015-11-16T00:30:00.000000Z 2015-11-16T10:30:00.000000Z`
`3B 3017  -- DPZ         250.0 2015-11-17T00:30:00.000000Z 2015-11-17T10:30:00.000000Z`
`3B 3017  -- DPZ         250.0 2015-11-21T23:30:00.000000Z 2015-11-22T09:30:00.000000Z`
`3B 3017  -- DPZ         250.0 2015-11-22T23:30:00.000000Z 2015-11-23T09:30:00.000000Z`
`3B 3017  -- DPZ         250.0 2015-11-23T23:30:00.000000Z 2015-11-24T09:30:00.000000Z`
`3B 3017  -- DPZ         250.0 2015-11-24T23:30:00.000000Z 2015-11-25T09:30:00.000000Z`
`3B 3017  -- DPZ         250.0 2015-11-25T23:30:00.000000Z 2015-11-26T09:30:00.000000Z`
`3B 3017  -- DPZ         250.0 2015-11-26T23:30:00.000000Z 2015-11-27T09:30:00.000000Z`

Desired output for station 1007:
`3B 1007  -- DPZ         250.0 2015-11-10T00:30:00.000000Z 2015-11-10T10:30:00.000000Z`
`3B 1007  -- DPZ         250.0 2015-11-11T00:30:00.000000Z 2015-11-11T10:30:00.000000Z`
`3B 1007  -- DPZ         250.0 2015-11-12T00:30:00.000000Z 2015-11-12T10:30:00.000000Z`
`3B 1007  -- DPZ         250.0 2015-11-13T00:30:00.000000Z 2015-11-13T10:30:00.000000Z`
`3B 1007  -- DPZ         250.0 2015-11-14T00:30:00.000000Z 2015-11-14T10:30:00.000000Z`
`3B 1007  -- DPZ         250.0 2015-11-15T00:30:00.000000Z 2015-11-15T10:30:00.000000Z`
`3B 1007  -- DPZ         250.0 2015-11-16T00:30:00.000000Z 2015-11-16T10:30:00.000000Z`
`3B 1007  -- DPZ         250.0 2015-11-17T00:30:00.000000Z 2015-11-17T10:30:00.000000Z`

Desired output from this example for station 3017:
`3B 3017  -- DPZ         250.0 2015-11-21T23:30:00.000000Z 2015-11-22T09:30:00.000000Z`
`3B 3017  -- DPZ         250.0 2015-11-22T23:30:00.000000Z 2015-11-23T09:30:00.000000Z`
`3B 3017  -- DPZ         250.0 2015-11-23T23:30:00.000000Z 2015-11-24T09:30:00.000000Z`
`3B 3017  -- DPZ         250.0 2015-11-24T23:30:00.000000Z 2015-11-25T09:30:00.000000Z`
`3B 3017  -- DPZ         250.0 2015-11-25T23:30:00.000000Z 2015-11-26T09:30:00.000000Z`
`3B 3017  -- DPZ         250.0 2015-11-26T23:30:00.000000Z 2015-11-27T09:30:00.000000Z`

Please let me know if you want more background about these examples, or have questions--this is a longer comment/review than I usually post and it's possible I lost track of something, or that in trying to keep this a reasonable length I excluded something essential.  Also let me know if you want me to break these down into separate comments to make them easier to keep track of.

**Comment by hrotman-pic** [comment]
I just remembered another case that occurs (but fairly rare): Fairfield node experiment with multiple deployment epochs created manually, instead of created when the raw data are added to the PH5.  The example is from 19-024 (validated and archived).  The availability output has epochs repeated for a given SNCL, like other Fairfield multiple deployments.  

Here is the availability output using fix_460:
ph5availability -n master.ph5 -p . --station 1110 -S -a 2 -f t
#n s     l  c   q sample-rate                    earliest                      latest
1B 1110  -- GP1        1000.0 2019-08-07T23:24:58.996000Z 2019-08-19T18:30:25.000000Z
1B 1110  -- GP1        1000.0 2019-08-07T23:24:58.996000Z 2019-08-19T18:30:25.000000Z
1B 1110  -- GP1        1000.0 2019-08-07T23:24:58.996000Z 2019-08-19T18:30:25.000000Z
1B 1110  -- GP2        1000.0 2019-08-07T23:24:58.996000Z 2019-08-19T18:30:25.000000Z
1B 1110  -- GP2        1000.0 2019-08-07T23:24:58.996000Z 2019-08-19T18:30:25.000000Z
1B 1110  -- GP2        1000.0 2019-08-07T23:24:58.996000Z 2019-08-19T18:30:25.000000Z
1B 1110  -- GP3        1000.0 2019-08-07T23:24:58.996000Z 2019-08-19T18:30:25.000000Z
1B 1110  -- GP3        1000.0 2019-08-07T23:24:58.996000Z 2019-08-19T18:30:25.000000Z
1B 1110  -- GP3        1000.0 2019-08-07T23:24:58.996000Z 2019-08-19T18:30:25.000000Z

Here are the deploy and pickup times from the array table for each deployment epoch.
First epoch:
deploy_time/ascii_s=Wed Aug  7 23:13:37 2019
deploy_time/micro_seconds_i=607000
pickup_time/ascii_s=Sat Aug 10 19:22:00 2019
pickup_time/micro_seconds_i=0

Second epoch:
deploy_time/ascii_s=Sat Aug 10 19:22:00 2019
deploy_time/micro_seconds_i=1000
pickup_time/ascii_s=Thu Aug 15 16:57:00 2019
pickup_time/micro_seconds_i=0

Third epoch:
deploy_time/ascii_s=Thu Aug 15 16:57:00 2019
deploy_time/micro_seconds_i=1000
pickup_time/ascii_s=Mon Aug 19 18:30:25 2019
pickup_time/micro_seconds_i=236999

**Comment by timronan** [comment]
> ph5availability -n master.ph5 -p . --station 1110 -S -a 2 -f t

This is in the data set, and this repeated availability happens in master branch of ph5availability. The validator likely doesn't have a check for "manually created" experiments where it seems like this station was loaded twice. This is a good thing to know about, and should be thought about as a validator issue, but is out of scope for this PR. Availability is reporting the available data in the ph5 experiments. If data are duplicated in ph5, availability should be transparent and not inject logic to suppress this data issue.  It will allow us to find these sorts of issues in the future so the data can be fixed. 

```
#
#   Table row 1
/Experiment_g/Sorts_g/Array_t_001
        id_s=1110
        location/X/value_d=-117.1785892
        location/X/units_s=degrees
        location/Y/value_d=52.14861012
        location/Y/units_s=degrees
        location/Z/value_d=1974.8
        location/Z/units_s=m
        location/coordinate_system_s=geographic
        location/projection_s=WGS84
        location/ellipsoid_s=
        location/description_s=Converted from UTM Zone 11N
        deploy_time/ascii_s=Wed Aug  7 23:13:37 2019
        deploy_time/epoch_l=1565219617
        deploy_time/micro_seconds_i=607000
        deploy_time/type_s=BOTH
        pickup_time/ascii_s=Sat Aug 10 19:22:00 2019
        pickup_time/epoch_l=1565464920
        pickup_time/micro_seconds_i=0
        pickup_time/type_s=BOTH
        das/serial_number_s=1X1110
        das/model_s=ZLAND 3C
        das/manufacturer_s=FairfieldNodal
        das/notes_s=manufacturer and model not read from data file.
        sensor/serial_number_s=
        sensor/model_s=GS-30CT
        sensor/manufacturer_s=Geo Space
        sensor/notes_s=manufacturer and model not read from file.
        description_s=DAS: 1X1110, Node ID: 2921
        seed_band_code_s=G
        sample_rate_i=1000
        sample_rate_multiplier_i=1
        seed_instrument_code_s=P
        seed_orientation_code_s=1
        seed_location_code_s=
        seed_station_name_s=1110
        channel_number_i=1
        receiver_table_n_i=8
        response_table_n_i=0

#   Table row 2
/Experiment_g/Sorts_g/Array_t_001
        id_s=1110
        location/X/value_d=-117.1785892
        location/X/units_s=degrees
        location/Y/value_d=52.14861012
        location/Y/units_s=degrees
        location/Z/value_d=1974.8
        location/Z/units_s=m
        location/coordinate_system_s=geographic
        location/projection_s=WGS84
        location/ellipsoid_s=
        location/description_s=Converted from UTM Zone 11N
        deploy_time/ascii_s=Wed Aug  7 23:13:37 2019
        deploy_time/epoch_l=1565219617
        deploy_time/micro_seconds_i=607000
        deploy_time/type_s=BOTH
        pickup_time/ascii_s=Sat Aug 10 19:22:00 2019
        pickup_time/epoch_l=1565464920
        pickup_time/micro_seconds_i=0
        pickup_time/type_s=BOTH
        das/serial_number_s=1X1110
        das/model_s=ZLAND 3C
        das/manufacturer_s=FairfieldNodal
        das/notes_s=manufacturer and model not read from data file.
        sensor/serial_number_s=
        sensor/model_s=GS-30CT
        sensor/manufacturer_s=Geo Space
        sensor/notes_s=manufacturer and model not read from file.
        description_s=DAS: 1X1110, Node ID: 2921
        seed_band_code_s=G
        sample_rate_i=1000
        sample_rate_multiplier_i=1
        seed_instrument_code_s=P
        seed_orientation_code_s=2
        seed_location_code_s=
        seed_station_name_s=1110
        channel_number_i=2
        receiver_table_n_i=35
        response_table_n_i=0

#   Table row 3
/Experiment_g/Sorts_g/Array_t_001
        id_s=1110
        location/X/value_d=-117.1785892
        location/X/units_s=degrees
        location/Y/value_d=52.14861012
        location/Y/units_s=degrees
        location/Z/value_d=1974.8
        location/Z/units_s=m
        location/coordinate_system_s=geographic
        location/projection_s=WGS84
        location/ellipsoid_s=
        location/description_s=Converted from UTM Zone 11N
        deploy_time/ascii_s=Wed Aug  7 23:13:37 2019
        deploy_time/epoch_l=1565219617
        deploy_time/micro_seconds_i=607000
        deploy_time/type_s=BOTH
        pickup_time/ascii_s=Sat Aug 10 19:22:00 2019
        pickup_time/epoch_l=1565464920
        pickup_time/micro_seconds_i=0
        pickup_time/type_s=BOTH
        das/serial_number_s=1X1110
        das/model_s=ZLAND 3C
        das/manufacturer_s=FairfieldNodal
        das/notes_s=manufacturer and model not read from data file.
        sensor/serial_number_s=
        sensor/model_s=GS-30CT
        sensor/manufacturer_s=Geo Space
        sensor/notes_s=manufacturer and model not read from file.
        description_s=DAS: 1X1110, Node ID: 2921
        seed_band_code_s=G
        sample_rate_i=1000
        sample_rate_multiplier_i=1
        seed_instrument_code_s=P
        seed_orientation_code_s=3
        seed_location_code_s=
        seed_station_name_s=1110
        channel_number_i=3
        receiver_table_n_i=0
        response_table_n_i=0

#   Table row 4
/Experiment_g/Sorts_g/Array_t_001
        id_s=1110
        location/X/value_d=-117.1785892
        location/X/units_s=degrees
        location/Y/value_d=52.14861012
        location/Y/units_s=degrees
        location/Z/value_d=1974.8
        location/Z/units_s=m
        location/coordinate_system_s=geographic
        location/projection_s=WGS84
        location/ellipsoid_s=
        location/description_s=Converted from UTM Zone 11N
        deploy_time/ascii_s=Sat Aug 10 19:22:00 2019
        deploy_time/epoch_l=1565464920
        deploy_time/micro_seconds_i=1000
        deploy_time/type_s=BOTH
        pickup_time/ascii_s=Thu Aug 15 16:57:00 2019
        pickup_time/epoch_l=1565888220
        pickup_time/micro_seconds_i=0
        pickup_time/type_s=BOTH
        das/serial_number_s=1X1110
        das/model_s=ZLAND 3C
        das/manufacturer_s=FairfieldNodal
        das/notes_s=manufacturer and model not read from data file.
        sensor/serial_number_s=
        sensor/model_s=GS-30CT
        sensor/manufacturer_s=Geo Space
        sensor/notes_s=manufacturer and model not read from file.
        description_s=DAS: 1X1110, Node ID: 2921
        seed_band_code_s=G
        sample_rate_i=1000
        sample_rate_multiplier_i=1
        seed_instrument_code_s=P
        seed_orientation_code_s=1
        seed_location_code_s=
        seed_station_name_s=1110
        channel_number_i=1
        receiver_table_n_i=14
        response_table_n_i=0

#   Table row 5
/Experiment_g/Sorts_g/Array_t_001
        id_s=1110
        location/X/value_d=-117.1785892
        location/X/units_s=degrees
        location/Y/value_d=52.14861012
        location/Y/units_s=degrees
        location/Z/value_d=1974.8
        location/Z/units_s=m
        location/coordinate_system_s=geographic
        location/projection_s=WGS84
        location/ellipsoid_s=
        location/description_s=Converted from UTM Zone 11N
        deploy_time/ascii_s=Sat Aug 10 19:22:00 2019
        deploy_time/epoch_l=1565464920
        deploy_time/micro_seconds_i=1000
        deploy_time/type_s=BOTH
        pickup_time/ascii_s=Thu Aug 15 16:57:00 2019
        pickup_time/epoch_l=1565888220
        pickup_time/micro_seconds_i=0
        pickup_time/type_s=BOTH
        das/serial_number_s=1X1110
        das/model_s=ZLAND 3C
        das/manufacturer_s=FairfieldNodal
        das/notes_s=manufacturer and model not read from data file.
        sensor/serial_number_s=
        sensor/model_s=GS-30CT
        sensor/manufacturer_s=Geo Space
        sensor/notes_s=manufacturer and model not read from file.
        description_s=DAS: 1X1110, Node ID: 2921
        seed_band_code_s=G
        sample_rate_i=1000
        sample_rate_multiplier_i=1
        seed_instrument_code_s=P
        seed_orientation_code_s=2
        seed_location_code_s=
        seed_station_name_s=1110
        channel_number_i=2
        receiver_table_n_i=41
```

**Comment by timronan** [comment]
The last batch of pushes solves the issues brought up of @hrotman-pic. Can you please retest this Pull request and leave a comment?

Thanks for the help.

**Comment by hrotman-pic** [comment]
@timronan here's a query from 19-024 that didn't result in the sample rate warning I mentioned:
`ph5availability -n master.ph5 -p . --station 1110 -S -a 2 -f t`

Here's a query that from 19-024 did result in the sample rate warning (warning printed once):
`ph5availability -n master.ph5 -p . --station 1111 -S -a 2 -f t`

The warning is new (and I know it is 'just' a warning), so I'm at a loss about where it came from.

**Review by hrotman-pic — APPROVED** [review]
It looks like all the test cases handle availability well with these updates, and this works as expected.  Thank you.

**Comment by timronan** [comment]
Warning has been updated to say "Using sample rate from DAS Table XXXXX." The sample raet is sometime taken from the array table and other time taken from the DAS table. In the cases where the data table sample rate it used this warning will be thrown. Because this PR seems to pass all of the logical test for PH5 availability I think it should be merged.

**Pull request merged**
