### PR TITLE
Fixed date-time format in ph5tostationxml.py

### PR DESCRIPTION
**Pull request by gbbofh**
### What does this PR do?

Fixes malformed time format string to be compliant with stationxml schema.

### Relevant Issues?

This bug was reported in Issue #432 

### Checklist
- [x] This PR is not directly related to an existing issue (which has no PR yet).
- [x] All tests pass.
- [x] Any new or changed features have are documented.
- [x] Changes have been added to `CHANGELOG.txt` .
- [x] First time contributors have added your name to `CONTRIBUTORS.txt` .

### CODE REVIEW

**Comment by dsentinel** [comment]
1. Are any of the other datetimes also non StationXML compliant i.e station, channel.../ start, endtimes. It looks like obspy did a blanket change of time time representations in https://github.com/obspy/obspy/pull/2015
2. Create an issue with obspy to address this and related issues.
3. Workaround until obspy is corrected; set `inventory.created = ` correct string, after the created time is automatically set and before writing out to StationXML file.

**Comment by gbbofh** [comment]
On further investigation, it looks like the version of obspy installed via the packaging with ph5 is v 1.1. This version uses a method `_format_time` to format the `UTCDateTime` passed to the `Inventory` constructor, by accessing the individual class fields. If a `str` object (such as is returned by `strftime`) is passed, an exception will be raised.

Updating to 1.2 fixes the issue because all of the calls to `_format_time` were replaced by casting the time object to `str` and letting the cast handle the formatting appropriately. Passing a `str` returned from `datetime.strftime()` now works, however changing the `datetime.now()` call to `UTCDateTime.now()` produces the appropriate formatting as well -- I believe this will work regardless of whether or not it is obspy version 1.2 or obspy version 1.1. Is there a particular reason that `UTCDateTime` objects are used elsewhere in ph5tostationxml, but not in the inventory creation?

**Comment by gbbofh** [comment]
@timronan The produced xml files now seem to pass the validator. This should be ready for your review at your earliest convenience. Please let me know if there is anything you think should be changed or handled differently.

**Comment by timronan** [comment]
It looks like this branch has a flake8 failure, once that is fixed I'll try and get to reviewing it at the beginning of next week. 11/23/2020.

**Comment by gbbofh** [comment]
Thank you for pointing that out. I've pushed a fix for the formatting.

**Review by timronan — APPROVED** [review]
After running this pull request against a number of test cases it seems to be working as expected. It seems like using Obspy's UTCDateTime is a good idea because it seems to be internally consistent with the other timestamps in ph5tostationxml. Following Obspy's lead will keep us consistent with the Obspy code stack which seems like it to desirable for PH5 and other IRIS data formats.

**Comment by timronan** [comment]
@gbbofh this PR seems ready to merge from my prescriptive. Do you have any issues with me performing the merge? Sorry we have been sitting on this one for a while.

**Comment by gbbofh** [comment]
> @gbbofh this PR seems ready to merge from my prescriptive. Do you have any issues with me performing the merge? Sorry we have been sitting on this one for a while.

No issues here. Feel free to merge at your earliest convenience.

**Review by timronan — APPROVED** [review]

**Pull request merged**
