### PR TITLE
Refactored ph5tomsAPI.py and removed unnecessary code.

### PR DESCRIPTION
**Pull request by nick-iris**
I changed the following:

- Add reqtype argument so that certain behaviors are more explicit
- Remove unused dasskip argument
- Move validation for required request type arguments to a separate validate method:
  - For request by shot: `length` is required
  - For fdsn request: `starttime` and `endtime` are required
- Removed code that would never be executed based on the request type restrictions
- Improved error handling

### CODE REVIEW

**Comment by derick-hess** [comment]
We need to make it where start time and end time aren't required for the command line. 
A user should be able to convert their data with a command like:

ph5toms -n master -p /storage/GeoGirls/ -f MSEED -o ~/mseed

**Comment by nick-iris** [comment]
Okay I'll change it to use the deploy and pickup dates in no starttime or endtime are entered.

**Comment by nick-iris** [comment]
Should I just get rid of the `validate` method?

If I remove the validate method, we should probably set a default value for `length`. Additionaly, if the `reqtype` is FDSN and `starttime` and `stoptime` aren't defined, then use the deploy and pickup date/times.

Also, I noticed that there is currently a argument called `use_deploy_pickup`. I think this can be removed as an option, and the program should always ignore anything outside of the deploy/pickup dates as per the discussion we had with Rick and Bruce.

**Comment by derick-hess** [comment]
use_deploy_pickup can be removed. It was used in previous versions and was a flag that could be set in ph5 but ph5toms doesn't need to use it. 

I think for now we can ignore any data outside deploy pickup, but remember this is also a field tool that PIS will be using while initially creating and manipulating their data so they will need access from the command line to fully work with their data so we will have to address that as well.

**Comment by nick-iris** [comment]
Absolutely, we definitley need the command line to work well. I didn't realize that they make requests without start and end times. I'll have additional updates for you shortly.

**Comment by derick-hess** [comment]
I am starting to write a program that will test a PH5 archive and give warnings, errors, and suggestions for fixing the PH5 archive. I will add code in this that will inform the user if data exists beyond the pickup time and how much data is there. That way a PI can use this information to determine if they need to change the pickup times etc, while still in the field and finalize it before its ready for archiving at the DMC.

**Comment by nick-iris** [comment]
That's a good idea.

Maybe we should keep the `use_deploy_pickup` option for PIs in case they want to look at data outside of the deploy/pickup range? I'll just set the default for this argument to True.

After this I am planning to start pulling a lot of the repetitive code from ph5tomsAPI.py, ph5toexml.py, and ph5tostationxml.py into a ph5utils.py module. It will make the three APIs a lot easier to maintain moving forward, by minimizing the number of places code needs to be changed. Thoughts?

**Comment by nick-iris** [comment]
It also might be good to through an exception is someone tries to use the ph5tomsAPI.py script on a PN3 version experiment. Is the easiest way to tell this based on the addition of the _net_code_s_ code in Experiment_t?

**Comment by derick-hess** [comment]
checking for net_codes_s would be the fastest way to check if it is pn3 or pn4.

**Comment by derick-hess** [comment]
ph5utils.py makes a lot of sense and would clean up the code base.

**Comment by nick-iris** [comment]
@derick-hess I think I fixed all of the problems remaining from the last commits. 

Just FYI - The addition of the reqtype option was necessary since we could not longer rely on shotline and eventnumbers being set as a way to tell if the reqtype=shot. If shotline=None or eventnumbers=None then wildcards are assumed just like the other options.

**Comment by nick-iris** [comment]
Rebased and forced pushed to master. I'm ready to merge it you're happy with the changes and all tests pass.

**Pull request merged**
