### PR TITLE
Improve the way setup.py handles c_dependencies

### PR DESCRIPTION
**Pull request by nick-iris**
In the current (v4.1.2) and older versions of PH5, the c dependencies in the ~/ph5/core/c_dependencies/ directory get built separately from the PH5 package. This causes problems when deploying from pip.

I created a new test release at https://test.pypi.org/manage/project/ph5/release/4.1.2-2/ that fixes this issue, by properly including these dependencies.

### CODE REVIEW

**Comment by derick-hess** [comment]
Thanks Nick. I'll test this out today

**Comment by derick-hess** [comment]
Should we also have ti check for obspy and inform user to install via anaconda?

**Comment by nick-iris** [comment]
No need to check for `obspy` as it will install with `pip` as long as `numpy` is already installed.

In my opinion, the huge `PyQt4` dependency is the biggest remaining issue with the setup.py. Ideally this should not be required for a standard installation of `PH5`.

Perhaps the small subset of commands requiring `PyQt4`, such as `pforma`, should raise a warning if it is not installed, rather than preventing the user from installing the entire `PH5` package?

**Comment by nick-iris** [comment]
FYI, for testing purposes you can install from the test release using:

```
pip install https://test-files.pythonhosted.org/packages/af/e1/e427177cebdc65503642c171ddb1376cb34950f4f1e7429b5d4ec02ceed5/ph5-4.1.2-2.tar.gz
```

**Comment by derick-hess** [comment]
Then we can just raise a warning so users can install pyqt5 if they want to use ph5_gui

**Comment by nick-iris** [comment]
`PyQt5` is a good start. You may want to design the program in such a way that the GUI is an optional convenience, and where users can achieve the same tasks that `ph5_gui` does via the command line. That way `PyQt5` may be viewed as an optional dependency. 

Are `ph5view`, `noven`, `pforma`, `kefedit` and `experiment_t_gen` all being replaced by `ph5_gui`?

**Comment by derick-hess** [comment]
Yeah, ph5_gui will replace them all. I'll try to also make a command line "wizard" to go with ph5_gui to make PyQt5 completely optional

**Comment by nick-iris** [comment]
What is the goal of `ph5_gui`? Is it to provide a step-by-step "wizard" for users to construct a ph5 experiment from scratch?

**Comment by derick-hess** [comment]
Yeah it will be a step by step wizard, as well as editing metadata, offline map view of metadata, and viewing waveforms

**Comment by nick-iris** [comment]
Thanks. Once you get a prototype, I'm happy to test it out and provide feedback.

**Comment by derick-hess** [comment]
So far need to add the subprocess 32 module as a requirement and I'm going to test this on other machines but it seems letting pip install matplotlib creates an error having to do with using virtual environments., but if you install matplotlib using conda it's fine.  using pip for matplotlib also works fine when installing outside a virtual environment

**Comment by derick-hess** [comment]
Looking at matplotlib docs, it's actually an issue using pyqt4 as the backend for matplotlib in virtual environments when installed with pip.  Once we can get rid of pyqt4 it will be fine.

**Comment by nick-iris** [comment]
@derick-hess Should we try to merge this and fix #236? We probably should also fix the failing build before issuing another PH5 release. Some files are failing the flake8 check.

**Comment by derick-hess** [comment]
That sounds good. Just have that issue with  pip installing pyqt4 right now. Letting pip install pyqt4 results in an issue with matplotlib.

**Comment by derick-hess** [comment]
I am working on the new PH5 GUI that uses pyqt5. It will also be the only graphical program in PH5 and can be optional for those that just want command line only. We can go ahead and merge this, fix the flake8 errors, and advise people to still use conda for now.

**Comment by nick-iris** [comment]
Are you going to put the PH5 GUI in a separate project so that it is not part of the base install?

**Comment by derick-hess** [comment]
I'm not sure yet. Either that or create a flag that installs command line only and skips installing it and any dependencies that only it needs.

**Comment by derick-hess** [comment]
I added warnings for PyQt or PySide to all gui programs and I added subprocess32 to setup.py. @nick-iris I think this is ready to merge

**Pull request merged**
