### PR TITLE
Allow wildcards for dataselect shot-id and shotline arguments. Fix #39.

### LINKED ISSUE #39: Add wildcard support for Shot-ID and Shotline
I've come to the conclusion that Shot-ID and Shotline should still accept wildcards even though shot-ids are not unique across shotlines.

### PR DESCRIPTION
**Pull request by nick-iris**
I've refactored ph5tomsAPI.py to accept wildcards for shot-id and shotline. It was a little bit trickier than I had originally anticipated.

### CODE REVIEW

**Comment by derick-hess** [comment]
testing now

**Comment by derick-hess** [comment]
I'll add that in the the argument parser while I'm testing

**Comment by nick-iris** [comment]
I just added it, but feel free to make any necessary modifications.

**Comment by nick-iris** [comment]
@derick-hess Did you get a chance to look these changes over?

Depending on how long it takes to read the entire event table, we could change this code to read all events if the `shotline` and `shotid` arguments are not set. This would avoid having to add the reqtype parameter to distinguish whether or not to read the event info.

i.e.
https://github.com/PIC-IRIS/PH5/blob/1b5c67d221793d8bb01de8c58ed73821f598ce86/kitchen/ph5tomsAPI.py#L655-L677

**Comment by derick-hess** [comment]
I  checked it over and everything works fine. The event table most of the time is going to have significantly less metadata than the array table. We could loop through the event table in the same manner as i do the array table and that would solve the reqtype issue I think.

**Comment by nick-iris** [comment]
Would the following raise an exception if no events are present? This might break on experiments without events.

https://github.com/PIC-IRIS/PH5/blob/1b5c67d221793d8bb01de8c58ed73821f598ce86/kitchen/ph5tomsAPI.py#L661-L668

Maybe it should be changed to:
```
    try:
        event_t = self.ph5.Event_t[
            shotline]['byid'][shot]
        start_times.append(event_t['time/epoch_l'])
        self.evt_lat = event_t['location/Y/value_d']
        self.evt_lon = event_t['location/X/value_d']
    except Exception:
        continue

```

**Comment by nick-iris** [comment]
Can the events table ever be empty? It seems like the arrays table always needs to have data so it it works to always loop over its contents.

If the events table could be empty, then I don't think that always looping over it would work.

**Comment by nick-iris** [comment]
I think I could remove the reqtype argument and instead do this:

 ```
   if matched_shot_lines and matched_shots:
        # request by shot
        for shotline in matched_shot_lines:
            for shot in matched_shots:
                try:
                    event_t = self.ph5.Event_t[
                        shotline]['byid'][shot]
                    start_times.append(event_t['time/epoch_l'])
                    self.evt_lat = event_t['location/Y/value_d']
                    self.evt_lon = event_t['location/X/value_d']
                except Exception:
                    raise PH5toMSAPIError("Error reading events table.") 
            cuts_generator.append(self.create_cut(experiment_t, station, seed_station, station_list, 
                                   start_times, deployment, st_num, matched_shot_lines))
    else:
        # fdsn request
        cuts_generator.append(self.create_cut(experiment_t, station, seed_station, station_list, 
                               start_times, deployment, st_num, matched_shot_lines))
```

**Comment by nick-iris** [comment]
I think this could be merged if you don't object.

**Comment by derick-hess** [comment]
I run a quick test and review as soon as i get back to the office from lunch

**Pull request merged**
