### PR TITLE
Optimize APIs

### PR DESCRIPTION
**Pull request by nick-iris**
The station service is way too slow on the production server, which is bogged down by other requests to the FDSN Web Services. We are going to need to optimize the APIs as much as possible.

I've just added a check to ph5tostationxml.py so that it will only read the DAS tables when it needs to. Reading the das tables is slow. 

@derick-hess and @rsdeazevedo Could you please help me work on optimizing the APIs? There are some optimization tips on the PyTables website that may also be of some help (http://www.pytables.org/usersguide/optimization.html).

### CODE REVIEW

**Comment by derick-hess** [comment]
On Tuesday I'll rewrite ph5tostationxml to not use access the  das table.  I should be able to write it to only access the array table receiver table and response table.  That should significantly speed things up

**Comment by derick-hess** [comment]
It should be a relatively easy change to have to not read the Das_t at all anymore. I think this is going to speed things up a ton.  I'll have a fix up this afternoon.

**Comment by derick-hess** [comment]
receiver_n_i and response_n_i are currently held in the das_t. It needs to be here for data reasons, but we are also going to modify the array table to hold receiver_n_i and response_n_i. This will eliminate the need to read all the das tables at all when only metadata is needed and should significantly speed up ph5tostationxml and ph5toexml. I'm going to work on the script for this today, Steve is going to update columns.py for the minor structural change to PH5 and then I will also update the wiki to reflect the change.

**Comment by nick-iris** [comment]
Thanks for the help Derick. I am certain that this will provide a significant performance improvement. Keep me posted on your progress. Once you're finished, I'll deploy the changes to PH5 Beta for final testing.

**Comment by derick-hess** [comment]
Finished the script to update PH5 experiments with the new structure. I need to write 2 small methods in ph5API this morning to access response and receiver table by n_i, then change a few lines in ph5tostationxml and it should be done. I expect to have this done today

**Comment by nick-iris** [comment]
Thanks for the quick turn around on this @derick-hess. Is this ready for review?

**Comment by derick-hess** [comment]
Yeah ready for review. I have already updated the experiments in the pn4 directory with the new array structure. The n_i numbers are also still in the das_t as well so it shouldn't break any old code that accesses the response information through the das_t

**Comment by nick-iris** [comment]
Okay sounds good. Is there any code that still accesses the n_i numbers through the das_t? Perhaps dataselect?

**Comment by derick-hess** [comment]
the web service dataselect currently doesn't, but if in the future PH5 supported more data formats that had the response information as part of the data output the n_i number in the das_t would make data output faster

**Comment by nick-iris** [comment]
Great improvement, thanks a lot for this. Returning StationXML for all experiments at the channel and response level is now on par with station level requests. 

I've deployed this to the production endpoint in case you want to hit it with some requests. We'll also want to update any experiments in the /pn4-beta directory, including Wavefields.

- https://service.iris.edu/ph5/station/1/query?level=channel&nodata=404
- https://service.iris.edu/ph5/station/1/query?level=response&nodata=404

In my opinion this is can be merged now. Once the RESP files are loaded in the /pn4 experiments and Wavefields we can deploy the Web Services publicly in my opinion.

**Comment by derick-hess** [comment]
Okay cool. I  will probably have all the response info loaded into the current pn4 experiments today and will update wavefields with the new array structure and it's response info as soon as it's finished uploading in the next day or two.

**Comment by nick-iris** [comment]
@derick-hess do we still need to be calling: `self.ph5.read_das_g_names()` ?

**Comment by derick-hess** [comment]
I don't think that needs to be called anymore.

**Comment by nick-iris** [comment]
Awesome I just removed that method call and it sped up the station service by ~3 additional seconds.

**Pull request merged**
