### PR TITLE
Fixes 1 second bug found occasionally in node data

### PR DESCRIPTION
**Pull request by derick-hess**
obspy_trace.stats.starttime.microsecond = (start_time_micro_seconds) interacted strangely with node data sometimes causing a 1 second offset. 

Also made sure floating point version of trace.start_time.epoch() was passed to obspy

### CODE REVIEW

**Comment by derick-hess** [comment]
There may be other changes on this as well coming tomorrow but this fixes the major bug.

**Comment by nick-iris** [comment]
Thanks. Lets keep the pull request open until the other changes are added. We should try to merge this and the other pull requests before Monday so we are ready to release.

**Comment by nick-iris** [comment]
We probably shouldn't have "BETA" in version number if it is going to be used for the production web services. I think we should remove it, what do you think?

**Comment by derick-hess** [comment]
yeah we can remove it.

**Comment by derick-hess** [comment]
This bug doesn't show up in any experiment data at the dmc or any other experiment data we have here .It only showed up on some nodes we were testing on our pier here at the PIC, but it showed that this bug could potentially happen.

**Comment by nick-iris** [comment]
Have these changes fixed the bug? Should we merge?

**Comment by derick-hess** [comment]
We can merge. This bug has been fixed. I will create another pull request when I start on the 1 sample start time bug

**Pull request merged**
