### PR TITLE
2017.206, Fixed to work properly with rtleap fixed raw files

### PR DESCRIPTION
**Pull request by derick-hess**

### CODE REVIEW

**Comment by derick-hess** [comment]
I think I see a few small things like TimeDOy needing to be renamed in the code to timedoy. I'll fix those after lunch

**Comment by nick-iris** [comment]
@rsdeazevedo For the future you'll want to create a developmental install of the latest "packaged" PH5 project since we changed some of the module and class names. To do this you just need to clone the PH5 repo and run `pip install -e .` in the top level project directory next to setup.py. 

With this type of install, as you make changes to the source code they are reflected in the your python environments installed PH5 package (i.e. in site-packages).

**Comment by rsdeazevedo** [comment]
There are likely a few of those lurking. The files 1302ph5.py and 
pn130.py are clean.

**Comment by rsdeazevedo** [comment]
I wasn't working in site-packages. I have a separate working area that 
is not part of the install or the clone of the master branch. I did a 
pull, then copied my changed files, added, committed, and pushed.

**Comment by nick-iris** [comment]
Yeah I have a developmental area too. When you do a developmental install it creates sym-links to your Python environments site-packages so that changes are automatically reflected in the installed version. 

You would clone the PH5 project to your development area and run `pip install -e .`. This creates an editable version of the installed PH5 project so that you don't have to copy anything.

**Comment by nick-iris** [comment]
Making changes is a little different now since PH5 is actually installed in your python environment. 

On my computer I did this:

**Initial Setup (You only do this once):**
1. In `/Users/nick/Development/workspace/` I ran `git clone https://github.com/PIC-IRIS/PH5.git`
2. In the cloned PH5 directory I ran `pip install -e .`. This created an developmental install in my python virtual environment. Any changes to the PH5 code base are recognized by the PH5 installation.

**Making changes:**
1. In the cloned PH5 project directory I pull the lastest version of the branch I'm working on
2. I make changes directly to this code which are automatically reflected in my python environments installed version of PH5 (the one installed in _Initial Setup step 2_).
3. Once my changes are ready, I commit & push them to the PH5 Git repo.

It's essentially the same as the ObsPy developer install process documented here https://github.com/obspy/obspy/wiki/Developer-Installation.

Let me know if you have any questions.

**Comment by rsdeazevedo** [comment]
Thanks Nick. I'll let you know how it goes.

**Comment by derick-hess** [comment]
The TimeDOY calls I saw that were incorrect were actually not in use and commented out. I just removed them. The timedoy calls that were in use in the code were already correct

**Comment by nick-iris** [comment]
@rsdeazevedo Were you able to successfully install PH5 in developer mode?

**Comment by rsdeazevedo** [comment]
Nick, I plan on doing that this weekend. Was busy last week with MATADOR 
II timing problems.

**Comment by rsdeazevedo** [comment]
Fixed a problem where 130toph5 was using reported number of samples rather than read number of samples in a rt-130 event.

**Comment by derick-hess** [comment]
Looks good. SInce i created this PR @nick-iris or @rsdeazevedo will have to approve

**Pull request merged**
