### PR TITLE
Complete rewrite of segytoph5

### PR DESCRIPTION
**Pull request by nick-falco**
### What does this PR do?

At the DMC we've recently underwent an effort to load some of the datacenter's SEG-Y holdings into PH5. This involved me writing a program for loading SEG-Y to into PH5. Additionally documentation was created by Eliana that explains how one can load SEG-Y into PH5.

I'd like to propose that we replace the currently broken segy2ph5.py program that is in the PH5 project with the new version that I've written. We should also provide a link to the SEG-Y to PH5 documentation on the PH5 Wiki. 

### Relevant Issues?
https://github.com/PIC-IRIS/PH5/pull/338

### Checklist
- [ ] This PR is not directly related to an existing issue (which has no PR yet).
- [ ] All tests pass.
- [ ] Any new or changed features have are documented.
- [ ] Changes have been added to `CHANGELOG.txt` .
- [ ] First time contributors have added your name to `CONTRIBUTORS.txt` .

### CODE REVIEW

**Comment by nick-iris** [comment]
When I have the time I'd like to add an integration test for this program that loads SEG-Y data into the test dataset. Additionally I'd like to add code for extracting event (shot) information from the SEG-Y headers and populate the PH5 Event_t table.

**Comment by dsentinel** [comment]
@nick-iris is this still live?
I'll give a review if so... sorry for the delay

**Comment by nick-iris** [comment]
Need to add at least one test

**Comment by timronan** [comment]
Was this ever reviewed?

**Comment by dsentinel** [comment]
I didn't give another review. I wasn't sure of the state of this branch. Nick may have gone in another direction, and this branch may be stale.
Is this functionality still desired?

**Comment by timronan** [comment]
This PR is out of scope for PH5's current resources allocation and level of maintenance.

**Pull request closed without merging**
