### PR TITLE
Add restricted data list to ph5toexml.py. 

### PR DESCRIPTION
**Pull request by nick-iris**
I've added support for a restricted data list to be added to ph5toexml.py.

The addition of this allows for the PH5 Dataselect program to skip restricted networks for requests by shot. This helps prevent timeouts when a request by shot on a restricted network is made.

### CODE REVIEW

**Comment by nick-iris** [comment]
I also fixed the shottext format header to include a required leading hash tag.

**Comment by nick-iris** [comment]
@derick-hess Is it okay if I merge this change? This doesn't affect the command line, and is required for the Web Services to work efficiently.

**Comment by derick-hess** [comment]
yeah go ahead and merge. Sorry I got behind I had a few software things that were due today  since they were going out to spain tomorrow. I should be back into the swing of PH5 development tomorrow afternoon

**Comment by nick-iris** [comment]
No worries, thanks Derick. Rebased and merged.

**Pull request merged**
