### PR TITLE
Autocorrect Kef file Timespans. 

### PR DESCRIPTION
**Pull request by timronan**
#What does this PR do?
This PR adds an optional additional argument, --auto-correct, to utilities/set_deploy_times.py. This argument permits the function to automatically change a .kef file's deploy times and pickup times to the floor and ceiling seconds that are defined by the start and end time of trace data to which the kef file refers. 

### Relevant Issues?
This code is associated with issue 310. 

### Checklist
- [X] This PR is not directly related to an existing issue (which has no PR yet).
- [X] All tests pass.
- [X] Any new or changed features have are documented.
- [X] Changes have been added to `CHANGELOG.txt` .
- [X] First time contributors have added your name to `CONTRIBUTORS.txt` .

### CODE REVIEW

**Comment by derick-hess** [comment]
Thanks Tim, I'll also give tyhis a look over. The passcal data group will want to add some documentation on this feature to their PH5t documentation along with a general guideline.

You will probably want to use this feature on most instrument types with the exception of the nodes. The time deploy/pickup times read for the nodes differs from the actual waveform time span in the nodes because the nodes have odd behavior. The nodes mark the deploy and pickup time in the their files of when real data starts and end. For some reason the nodes tend to record completely flat data for a random period of seconds to minutes both before and after their defined deploy/pickup times.

**Comment by timronan** [comment]
I forgot to add usage: 

To run the auto correct function:
`set_deploy_pickup_times --array-kef /PATH/TO/file.kef --nickname master.ph5 --ph5path /PATH/TO/master_and_mini.ph5 --auto-correct TRUE`

Thanks for looking into this function Derick. What is the flat data? Is that the instrument turning on and off/getting a gps lock?  Could we possibility trim this flat data before archiving it? The problem is that we receive data that falls outside of the metadata and is orphaned. The orphaned data then becomes an issue that we have to solve at the DMC. It seems to be  difficult and potentially dangerous for us to make an interpretation of which data are useful and which data should be trimmed. We were thinking that a solution could be to alter the metadata so it encompasses all of the waveform data. This  way all of the the waveform data will be available to the user community and they can make the decision of which data they find useful and which data are not.

**Comment by derick-hess** [comment]
I will see if I can get fairfield/magseis to respond about what is actually happening. I think it might be some internal testing or configuration. Sometimes the data is completely flat like the ADC isn't on and the datalogger is just writing 0's to the file for some reason. Other times it is noise like the ADC is on but the input is floating.  A solution to this would be fore the node reading portion of PH5 only writes the data between the deploy and pickup times of the nodes to a PH5 archive. This way there is no orphaned data outside the bounds.

**Comment by derick-hess** [comment]
Another thing that happens from time to time, but will happen less as the rt125(texan) instruments are deployed, there is no way to stop them recording when you pick them up. You pre-program a recording window or windows. If for some reason an experiment ends early then manually setting the deploy and pickup time is import because the instruments will stay recording and cant be stopped even after they are picked up. They will continue to record while they are driven around and brought back to the field center until they are offloaded.

This happens rarely though. In most cases the recording window has stopped the day or night before they are picked up.

**Comment by timronan** [comment]
Thanks for closing issue 310 and merging this pull request. We will be conservative as we use this PH5 feature moving into the future.

**Comment by nick-iris** [comment]
There were bugs found in the merged pull request that shouldn't be in the master branch. I've reverted the changes that were merged into master. @timronan Is going to make a new PR once all the issues are addressed.

**Comment by timronan** [comment]
This pull request was merged, closed, then the merging commit was retracted before the pull request was properly tested. After further investigation, the original pull request seems to be performing it's anticipated goal of: Taking input kef file and master.ph5 files and outputting  a new kef file that has the deploy and pickup dates adjusted to the time spans that are set by the waveform data. 

Here is a diff of an original vs auto adjusted .kef file. 

< 	deploy_time/ascii_s=Fri Mar 23 16:00:00 2018
< 	deploy_time/epoch_l=1521820800
---
> 	deploy_time/ascii_s=Thu Mar 22 16:00:00 2018
> 	deploy_time/epoch_l=1521734400

This pull request should be re-reviewed and discussed before determining whether the code stack needs to be rewritten.  Every test I have conducted indicates that this branch is working correctly.

**Comment by timronan** [comment]
The --auto-correct function output a kef file with start and end times that reflect those that are output by ph5api.get_extent function. Note, this is the function that is also used by ph5_validate. 

A little bit of background, ph5api.get_extent works by getting the start_times from the first and last DAS record. The end time is made by taking the start time of the last DAS record adding the number of samples/sample rate for that record. This extent is returned and the .kef file is update. 

From get_extent:
```
Start_time: 1521734400.0, End_time: 1521853195.0, ID_S: 1001
```

from original kef file to be validated:

```
Start_time: 1521734400, End_time: 1521766800, ID_S: 1001
```
PH5 Validation result:
```
 Station 1001 Channel 1
 0 error, 2 warning, 0 info
 -=-=-=-=-=-=-=-=-
 WARNING: No station description found.
 WARNING: Data exists after pickup time: 86395 seconds
 -=-=-=-=-=-=-=-=-
```

From the autocorrected kef:
```
deploy_time/epoch_l=1521734400, pickup_time/epoch_l=1521853195, id_s=1001
```

so all of the functions are consistent with the others. After converting the autocorrected kef and validating:
```
 -=-=-=-=-=-=-=-=-
 Station 1001 Channel 1
 0 error, 1 warning, 0 info
 -=-=-=-=-=-=-=-=-
 WARNING: No station description found.
 -=-=-=-=-=-=-=-=-
```
the time lag error goes away.

**Comment by nick-iris** [comment]
@timronan You should try this on an example where there are multiple epochs for a given station/channel.

**Comment by timronan** [comment]
A good example for an experiment with multiple epochs is 16-006 in pn4-stage. 

Before running the the --auto-correct function ph5_validate returns:

```
 -=-=-=-=-=-=-=-=-
 Station 1001 Channel 1
 0 error, 2 warning, 0 info
 -=-=-=-=-=-=-=-=-
 WARNING: No station description found.
 WARNING: Data exists after pickup time: 88432 seconds
 -=-=-=-=-=-=-=-=-
 Station 1002 Channel 1
 0 error, 2 warning, 0 info
 -=-=-=-=-=-=-=-=-
 WARNING: No station description found.
 WARNING: Data exists after pickup time: 88444 seconds
```

After running the auto-correct function ph5_validate returns:

```
 -=-=-=-=-=-=-=-=-
 Station 1001 Channel 1
 0 error, 1 warning, 0 info
 -=-=-=-=-=-=-=-=-
 WARNING: No station description found.
 -=-=-=-=-=-=-=-=-
 Station 1002 Channel 1
 0 error, 1 warning, 0 info
 -=-=-=-=-=-=-=-=-
 WARNING: No station description found
```

The branch is ready to be reviewed .

**Pull request merged**
