### PR TITLE
Ref 480 nuke table

### PR DESCRIPTION
**Pull request by damhuonglan**
#### nuke_table
Modify nuke_table to give a cleaner way of deleting das from PH5. 
Ex: `nuke_table -n master.ph5 -D 3X500`

- The current way is truncate Das_t for the given das so tools cannot detect data for the das. However, link to das still exist and all tables related to das still can be seen using HDFView which is very confusing.

- The new way is keep the das's data intact, but remove the external link to the minifile. This way, tools including HDFView, cannot see the das. But all the tables are still in minifile for roll back in need. Additionally, to keep the data consistent, entries relate to the das in index_t and array_t are removed when running the tool.

The original way is still be able to perform with flag `--trunc`:
Ex: `nuke_table -n master.ph5 -D 3X500 --trunc`

Log is set for nuke_table in this PR

#### create_ext
In order to roll back nuke_table for Das, a way to create external link is needed. create_ext provides a way to do that. This tool is also benefit for table with waveform but missing metadata so that the external link can be created to complete the data when metadata is found.
Ex: `create_ext -n master.ph5 -D 3X500 -m miniPH5_00001.ph5`

In order to look for the minifile contaning waveform data for a Das, use flag '-s':
Ex: `create_ext -n master.ph5 -D 3X500 -s`

### Requirements
Remember to install new command using `pip install -e .` in ph5 conda environment, under PH5 root folder.

### Relevant Issues?
#480

### Checklist
- [ ] This PR is not directly related to an existing issue (which has no PR yet).
- [x] All tests pass.
- [x] Any new or changed features have are documented.
- [x] Changes have been added to `CHANGELOG.txt` .
- [ ] First time contributors have added your name to `CONTRIBUTORS.txt` .

### CODE REVIEW

**Comment by hrotman-pic** [comment]
@damhuonglan do you want me to try to reproduce the error I found that caused traceback messages, with another experiment?

**Comment by hrotman-pic** [comment]
The test cases previously causing errors with delete_table are working now.

The new delete_table correctly detects which array(s) the DAS to be deleted is in, and modifies those.  Backup array table(s) and index table are written out successfully.  After that, the deleted DAS is no longer visible in the DAS table list, and I confirmed visually that the deleted DAS is not in the array table(s) and index table in the PH5.

I have used create_ext on all of the test cases I selected.  If the mini file specified is not the one that contains the waveforms for the DAS, create_ext provides an error message with the correct minifile, for example: 
`ERROR: Minifile for Das 10679 in index_t is miniPH5_00001.ph5 while the given minifile is miniPH5_00040.ph5.`


Test case PH5s:
Fairfield, 1 array
RT130, 2 arrays (deleted DAS in 1 array)
SmartSolo, 1 array [subset of actual experiment]
Texan, 1 array
Texan, 12 arrays (deleted DAS in 4 arrays)

@ascire-pic @timronan (and whoever else may have thoughts on this) do these have sufficient diversity of datalogger types & numbers of arrays, in your opinion?

Question applicable to the node PH5s: it looks like the deleted DAS remains in Map_Index_t.  (If I remember right, that table is not used very much.)  Is this OK, or potentially confusing or misleading?

I wanted to ask these questions while I am still testing the results of create_ext.  I will re-validate each test case PH5 and attempt to write out data.

**Comment by hrotman-pic** [comment]
I will describe what I was thinking of yesterday.  Please let me know if this makes sense or not.

The current way of deleting a Das table includes writing out the table to a kef file (like Das_t_11080_2020009_00.kef).  This leaves a useful record so someone looking at the PH5 later can see what Das table(s) got deleted, if all the files stay together.  I think it would be helpful to have a file that is automatically created with information about what Das table(s) got deleted, in case notes about what Das have been deleted are lost by the time the metadata are found.  I do not recommend creating a Das_t_ kef backup because I think that would create confusion between the new way and using --trunc, but I am thinking of a log file with that information.

One idea for log file: create a delete_table (or nuke_table) log file, with a time stamped record of all table deletions, formatted similarly to the kef2ph5.log file, such as:
Fri Aug 27 14:06:28 2021*: Deleted Das_t_1X1104 from miniPH5_00004.ph5
Fri Aug 27 14:06:29 2021*: Deleted Array_t_001 from master.ph5 and created backup Array_t_001_2021027_00.kef
However, I don't know if keeping a log of tables that are deleted and have a backup created is needed or useful to the user.

My other idea is to create a delete_das log that only contains information about deleting the Das: the timestamp when the das was deleted, the serial number of the deleted das, and the minifile the das belongs to.  Then some information on how to rollback. For example:
[2021-11-29 17:20:42,606] - ph5.utilities.nuke_table - INFO: ['/home/ph51/anaconda3/envs/ph5/bin/nuke_table', '-n', 'master.ph5', '-D', '1X1104']
[2021-11-29 17:20:42,668] - ph5.utilities.nuke_table - INFO: Das 1X1104 is deleted from miniPH5_00004.ph5.
[2021-11-29 17:20:42,680] - ph5.utilities.nuke_table - INFO: To rollback this deletion, you will need the Array_t_001 and Index_t kef files that have just been written to the working directory.  Run delete_table to remove the versions of these tables that currently exist in the PH5, and then load the Array_t_001 and Index_t kef files.  You can then run 'create_ext' to add Das back to master.  Please see PIC data group PH5 documentation on deleting and replacing tables if needed.  Note that if you remove additional Das tables, you will need to exercise caution in restoring the correct Array_t_001 and Index_t kef files to the PH5.

I am not sure if there is an unaddressed need for a delete_table log, but if there is, maybe these ideas could be combined if it is considered within the scope of this PR.  I am trying to think of how to make the updates in this PR easiest for a future user to utilize if the metadata are found and create_ext can be used, but others may have a different perspective (I might be trying to make it too easy).

**Review by hrotman-pic — APPROVED** [review]
I re-tested the same cases after the most recent commits.  All of them work for deleting a DAS the new way and using create_ext.  I tested the minifile scan in create_ext, and it correctly detects the mini file with the data.  Deletions are logged and the log includes what DAS S/N was deleted.

As far as I can tell, this works as intended & desired for all of the test cases I've used.

**Review by timronan — APPROVED** [review]
This looks really good and ready to merge. Thank you for the detailed test cases.

**Pull request merged**
