### PR TITLE
Use libmseed directly for ph5toms output

### PR DESCRIPTION
**Pull request by derick-hess**
Thank your for contributing to PH5

Before submitting a PR, please review the pull request guidelines:
https://github.com/PIC-IRIS/PH5/blob/master/CONTRIBUTING.md#submitting-a-pull-request

### What does this PR do?
This PR will move writing of miniseed away from obspy and to using libmseed directly,
### Checklist
- [x] This PR is not directly related to an existing issue (which has no PR yet).
- [ ] All tests pass.
- [ ] Any new or changed features have are documented.
- [ ] Changes have been added to `CHANGELOG.txt` .
- [ ] First time contributors have added your name to `CONTRIBUTORS.txt` .

- [ ] Update libmseed build to rename library based on OS
- [ ] PH5toms better handling of figuring out libmseed library name to load
- [ ] Use rt2ms as example for new method of mseed out

### CODE REVIEW

**Comment by derick-hess** [comment]
SO far what I have done is add libmseed to PH5, comple it and move the linux libraries to ph5/lib where it can be used by the libmseed wrapper. Will need to add more to the setup to make sure it also works for other operating systems.

Next up is to lazy import obspy in ph5toms so that obspy is only loaded when writing sac or formats othr than miniseed when needed.

After that create_trace in ph5toms needs to be modified to yield ph5 trace objects and metadata to a new miniseed writing method in the case of miniseed output.

**Comment by nick-iris** [comment]
@derick-hess I'm going to see if I can get this working using the libmseed that is already included in ObsPy.

**Comment by nick-iris** [comment]
@derick-hess The ObsPy libmseed wrapper is located at https://github.com/obspy/obspy/blob/master/obspy/io/mseed/headers.py. An example of importing it is as follows:

```
from obspy.io.mseed.headers import (HPTMODULUS, MS_NOERROR, MS_ENDOFFILE,
                                    MSFileParam, MSRecord, clibmseed)
```

Can we use this wrapper?

**Comment by derick-hess** [comment]
We probably can. How long does it take to import that wrapper? 
The wrapper I have now is already ready to go and uses the same trace data structure as PH5 does.

**Comment by derick-hess** [comment]
We could actually probably compile my wrapper against the compiled libmseed library in obspy. Just have to get it to consistently point to that library when building my wrapper...

**Comment by nick-iris** [comment]
The import was really slow:

```python
def timeit():
   import time
   start = time.time()
   from obspy.io.mseed.headers import (HPTMODULUS, MS_NOERROR, MS_ENDOFFILE,
                                        MSFileParam, MSRecord, clibmseed)
   end = time.time()
   print("import took %s seconds" % (end - start))
timeit()

>> import took 2.63371396065 seconds
```

**Comment by nick-iris** [comment]
How long does it take to import your wrapper?

**Comment by derick-hess** [comment]
@nick-iris importing mseed_py and pointing to the library. I'll change the way it points ot the library a bit to make it more robust. Probably follow the way Obspy points to the library based on OS.

```python

def timeit():
   import time
   start = time.time()
   from ctypes import cdll
   lib1 = cdll.LoadLibrary('ph5/lib/libmseed.so.2')
   import mseed_py
   end = time.time()
   print("import took %s seconds" % (end - start))
timeit()

>> import took 0.00399303436279 seconds
```

**Comment by derick-hess** [comment]
I've added lazy_import so that obspy functionality is only imported on use. I'm not sure I will be able to get to adding mseed out method.  It should be fairy straight forward  and fast ti implement using the write_mseed method as a guide found here

https://git.passcal.nmt.edu/passoft/rt2ms/blob/master/rt2ms/rt2ms.py

This code base uses the same wrapper.

**Comment by nick-iris** [comment]
Will likely take a different approach to improve miniSEED extraction performance.

**Pull request closed without merging**
