### PR TITLE
fixes #229

### LINKED ISSUE #229: ph5_validate checks
I just finished doing a thorough review of `ph5_validate`. Below I've created a list of items that go unchecked. Feel free to add to this if you think of any others.

The following should be added:

**Experiment_t Checks:**
- [x] Check if there is any timeseries data outside of the  experiment start/end time span limits. (Warning)
- [x] Check if a report number matches the pattern ##-###. Currently there is only a check for its existence. (Error)
- [x] Check if a SEED network code is between 1 and 2 characters. Currently there is only a check for its existence. (Error)
- [x] Check for `summary_paragraph_s`. (Warning)

**Array_t Checks:**
- [x] Check for `description_s`(Warning)
- [x] Check if a `seed_location_code_s` between 0 and 2 characters. Currently there is NO check for `seed_location_code_s`.(Error)
- [x] ~~Check if a `seed_channel_code_s` is 3 characters. Currently there is NO check for `seed_channel_code_s`.~~
- [x] Check for `location/Z/value_d`. Currently only location/X/value_d and location/Y/value_d are checked.(Warning)
- [x] Check for `das/serial_number_s`(Error)
- [x] Check for `sensor/serial_number_s`(Warning)

**Event_t Checks (if Event_t present)**
- [x] Check for `id_s`(Error)
- [x] Check for `description_s`(Warning)
- [x] Check for `location/coordinate_system_s`(Warning)
- [x] Check for `location/projection_s`(Warning)
- [x] Check for `location/ellipsoid_s`(Warning)
- [x] Check for `location/description_s`(warning)
- [x] Check for `location/X/value_d`(Error)
- [x] Check for `location/X/units_s`(Error)
- [x] Check for `location/Y/value_d`(Error)
- [x] Check for `location/Y/units_s`(Error)
- [x] Check for `location/Z/value_d`(Error)
- [x] Check for `location/Z/units_s`(Error)
- [x] Check for `time/epoch_l`(Error)
- [x] Check for `time/micro_seconds_i`(Error)
- [x] Check for `size/value_d`(Warning)
- [x] Check for `size/units_s`(Warning)
- [x] Check for `depth/value_d`(Warning)
- [x] Check for `depth/units_s`(Warning(

... Should we also have checks for Offset_t_XXX_XXX and Sort_t?

### PR DESCRIPTION
**Pull request by derick-hess**
Check if there is any timeseries data outside of the experiment start/end time span limits.

### CODE REVIEW

**Comment by derick-hess** [comment]
@nick-iris This should close #229 with the last ph5_validate check on the list

**Comment by derick-hess** [comment]
That's a good idea. You can modify the array tables to set their deploy and pickup times outside of the real data window. This checks each channel of every station to see it contains data outside the specified deploy and pickup time.

This is set to just be a warning for users, because there could be edge cases where a PI knows there is bad data at the end or beginning of an experiment that should be excluded and sets the deploy and pickup times to deliberately exclude that data, but we should warn just in case they just set the deploy/pickup wrong.

**Comment by dthomas1953** [comment]
OK, will give it a try..

**Comment by derick-hess** [comment]
realized I'll have to make a minor modification to this code.  For pickup the code is incorrect because it only gets the start time of the final window and doesn't add the length of the final window to the end time. I'll have a fix soon.

**Comment by dthomas1953** [comment]
OK, Standing by...

**Comment by derick-hess** [comment]
@dthomas1953 okay should be good to go now. I also moved the function for getting the time of fist and last sample to the API since that could be useful for other programs in the future.

**Comment by dthomas1953** [comment]
I noticed some oddities, so I re-ran the Castle Rock node data starting at pforma, using the latest version of ph5_validate. 
When I ran resp_load, I got some odd messages:
```
(ph5) spike:Sigma dthomas$ resp_load -n master.ph5 -a 1 -i input.csv
/Users/dthomas/miniconda3/envs/ph5/lib/python2.7/site-packages/matplotlib/font_manager.py:273: UserWarning: Matplotlib is building the font cache using fc-list. This may take a moment.
  warnings.warn('Matplotlib is building the font cache using fc-list. This may take a moment.')
[2019-01-29 01:04:05,541] - ph5.utilities.resp_load - INFO: Loaded ZLAND3C_250_1_12
[2019-01-29 01:04:06,740] - ph5.utilities.nuke_table - INFO: Writing table backup: Response_t_2019029_00.kef.
[2019-01-29 01:04:07,357] - ph5.utilities.kef2ph5 - INFO: Loading response_t.kef into master.ph5.
[2019-01-29 01:04:07,365] - ph5.utilities.kef2ph5 - INFO: Updated kef2ph5.log file.
usage: Version: 2018.268
tabletokef     --nickname ph5-file-prefix options
ph5tokef: error: unrecognized arguments: -k response_t.kef
[2019-01-29 01:04:08,504] - ph5.utilities.nuke_table - INFO: Writing table backup: Response_t_2019029_01.kef.
[2019-01-29 01:04:08,541] - ph5.utilities.resp_load - INFO: response_t.kef written into PH5
[2019-01-29 01:04:09,110] - ph5.utilities.kef2ph5 - INFO: Loading response_t.kef into master.ph5.
[2019-01-29 01:04:09,120] - ph5.utilities.kef2ph5 - INFO: Updated kef2ph5.log file.
[2019-01-29 01:04:14,760] - ph5.utilities.nuke_table - INFO: Writing table backup: Array_t_001_2019029_00.kef.
[2019-01-29 01:04:14,763] - ph5.utilities.nuke_table - INFO: 1 It worked.
[2019-01-29 01:04:15,353] - ph5.utilities.kef2ph5 - INFO: Loading array_t_1.kef into master.ph5.
[2019-01-29 01:04:15,386] - ph5.utilities.kef2ph5 - INFO: Updated kef2ph5.log file.
[2019-01-29 01:04:16,603] - ph5.utilities.nuke_table - INFO: Writing table backup: Array_t_001_2019029_01.kef.
[2019-01-29 01:04:16,606] - ph5.utilities.nuke_table - INFO: 1 It worked.
```
What caught my eye was 
```
ph5tokef: error: unrecognized arguments: -k response_t.kef
```
Later, I got an oddity with ph5_validate:
```
(ph5) spike:Sigma dthomas$ sort_kef_gen -n master.ph5 -a>sort_t.kef
(ph5) spike:Sigma dthomas$ keftoph5 -n master.ph5 -k sort_t.kef
[2019-01-29 01:05:13,178] - ph5.utilities.kef2ph5 - INFO: Loading sort_t.kef into master.ph5.
[2019-01-29 01:05:13,325] - ph5.utilities.kef2ph5 - INFO: Updated kef2ph5.log file.

(ph5) spike:Sigma dthomas$ ph5_validate -n m
master.ph5         miniPH5_00001.ph5  miniPH5_00002.ph5  miniPH5_00003.ph5
(ph5) spike:Sigma dthomas$ ph5_validate -n master.ph5
[2019-01-29 01:05:28,245] - ph5.utilities.ph5validate - INFO: Validating Experiment_t
[2019-01-29 01:05:28,246] - ph5.utilities.ph5validate - ERROR: 'NoneType' object is not iterable
Closing remaining open files:./master.ph5...done
```
Besides the nonetype error, there was no PH5Validate.log file created.

I'll go ahead and try editing the array.kef file to restrict deployment times, then nuke_table to clear tables, then keftoph5 -n master.ph5 -k array.kef to rebuild the tables and test the warning message.

Stand by.

**Comment by dthomas1953** [comment]
Tried it, got same result - can't see PH5Validate.log, it's not there.
```
(ph5) spike:Sigma dthomas$ ph5_validate -n master.ph5
[2019-01-29 01:34:24,323] - ph5.utilities.ph5validate - INFO: Validating Experiment_t
[2019-01-29 01:34:24,324] - ph5.utilities.ph5validate - ERROR: 'NoneType' object is not iterable
Closing remaining open files:./master.ph5...done
```

**Comment by derick-hess** [comment]
the first -k not found is a false positive for an error. Ive been trying to figure out why it does that. It loads everything correctly.

My guess is you don't have an experiment table loaded. It is isnt finding one so that variable is set to None. I will make an issue and fix that in ph5_validate to let user know that an experiment table isnt loaded.

**Comment by dthomas1953** [comment]
Looks lots better after the patch. 1st run thru, I again saw this on doing resp_load:
```
[2019-01-29 18:01:22,107] - ph5.utilities.kef2ph5 - INFO: Updated kef2ph5.log file.
usage: Version: 2018.268
tabletokef     --nickname ph5-file-prefix options
ph5tokef: error: unrecognized arguments: -k response_t.kef
...
[2019-01-29 18:01:29,491] - ph5.utilities.nuke_table - INFO: 1 It worked.
```
ph5_validate ran OK. Here's the first part; oddity is that every channel says __WARNING: Data exists after pickup time__, and this is before I adjusted the deploy/pickup times in array.kef.
```
(ph5) spike:Sigma dthomas$ cat ph5_validate.log
-=-=-=-=-=-=-=-=-
Exeriment_t
3 error, 1 warning, 0 info
-=-=-=-=-=-=-=-=-
ERROR: Network code is a permanent FDSN: Network code should be a temporary code.
ERROR: Experiment ID was not found: An experiment id (YY-XXX) is required.
ERROR: Invalid report number code . Must match pattern [0-9][0-9]-[0-9][0-9][0-9].
-=-=-=-=-=-=-=-=-
Exeriment_t
3 error, 1 warning, 0 info
-=-=-=-=-=-=-=-=-
WARNING: Summary Paragraph was not found: It is suggested you include a short summary paragraph describing the experiment or data
-=-=-=-=-=-=-=-=-
Station 101 Channel 1
0 error, 1 warning, 0 info
-=-=-=-=-=-=-=-=-
WARNING: Data exists after pickup time
-=-=-=-=-=-=-=-=-
```

I edited array.kef, changed the 1st three rows, 1st row changed epoch deploy time from 1518490383 to 1518494400 (i.e. 4:00:00), and epoch pickup time from 1518504911 to 1518498000 (i.e. 5:00:00). 2nd row I changed the ascii deploy time from 02:53:03 to 04:00:00, and pickup time from 06:55:11 to 05:00:00. 3rd row I changed both epoch and digital times.

Here's part of the ph5_validate log file:
```
-=-=-=-=-=-=-=-=-
Station 101 Channel 1
0 error, 2 warning, 0 info
-=-=-=-=-=-=-=-=-
WARNING: Data exists before deploy time
WARNING: Data exists after pickup time
-=-=-=-=-=-=-=-=-

-=-=-=-=-=-=-=-=-
Station 101 Channel 2
0 error, 1 warning, 0 info
-=-=-=-=-=-=-=-=-
WARNING: Data exists after pickup time
-=-=-=-=-=-=-=-=-

-=-=-=-=-=-=-=-=-
Station 101 Channel 3
0 error, 2 warning, 0 info
-=-=-=-=-=-=-=-=-
WARNING: Data exists before deploy time
WARNING: Data exists after pickup time
-=-=-=-=-=-=-=-=-
```

So it looks like the change in deploy times was detected when I changed the epoch times, but not the digital clock times. All channels again say "Data exists after pickup time".

**Comment by derick-hess** [comment]
All of ph5 only ever looks at the epoch times. The ascii times are just for humans. PH5_validate is actually correct in that there is data after the pickup time.  It looks like the Nodes might keep recording for a few minutes after they mark the last sample.

**Comment by dthomas1953** [comment]
OK, thanks for the clarification!

**Comment by derick-hess** [comment]
Many Texans will have data after as well. Since they don't shut off when you pick them up and may still be recording

**Comment by derick-hess** [comment]
are you sure you are using the correct one? check the code at lines 479,280,481. It should definitely be writing out to the log. This is what I get


-=-=-=-=-=-=-=-=-
Exeriment_t
1 error, 0 warning, 0 info
-=-=-=-=-=-=-=-=-
ERROR: Experiment_t does not exist. run experiment_t_gen to create table
-=-=-=-=-=-=-=-=-
Station 101 Channel 1
0 error, 1 warning, 0 info
-=-=-=-=-=-=-=-=-
WARNING: Data exists after pickup time: 221077 seconds
.
.
.
etc

**Comment by dthomas1953** [comment]
I re-pulled, it was already updated. Maybe there's something wrong with my method? Starting with a normal run, I edited array.kef in the Sigma folder to have 3 shots going from 4:00 tp 5:00 rather than 2:53-6:55. 
Then I nuked the table, 
```nuke_table -n master.ph5
```
Then I ran keftoph5, 
```
keftoph5 -n master.ph5 -k array.kef
```
Then I ran ph5_validate, and looked at the log. Re-did it, still no messages like " Data exists after pickup time: 221077 seconds".

**Comment by derick-hess** [comment]
Did you check those lines of code to see if they were there? I just completely deleted my PH5, re-cloned it, nd switched to the ph5_validate branch and it's definitely there and outputting the time.

**Comment by derick-hess** [comment]
Just in case try checking out master. Doing a git pull, then checking out ph5_validate

**Comment by dthomas1953** [comment]
Switched to master, pulled, switched back to ph5_validate, pulled, was current. I looked at /utilities/ph5validate.py, definitely had the write times lines at 479-481. 

Still not seeing the message in the validate log?!?

**Comment by derick-hess** [comment]
Not sure. Try editing ph5_validate and putting a message in there the running it. IF your message doesn;t show up you are somehow running the wrong version and it's not calling the right ph5_validate

**Comment by dthomas1953** [comment]
Silly me, I forgot to install between pulls. Working fine!
```
Station 101 Channel 1
0 error, 1 warning, 0 info
-=-=-=-=-=-=-=-=-
WARNING: Data exists after pickup time: 221077 seconds
-=-=-=-=-=-=-=-=-
Station 101 Channel 1
0 error, 2 warning, 0 info
-=-=-=-=-=-=-=-=-
WARNING: Data exists before deploy time: 3524 seconds
WARNING: Data exists after pickup time: 227988 seconds
-=-=-=-=-=-=-=-=-
Station 101 Channel 1
0 error, 1 warning, 0 info
-=-=-=-=-=-=-=-=-
WARNING: Data exists after pickup time: 221077 seconds
```

**Comment by nick-iris** [comment]
I have some more `ph5_validate` enhancements in PR #254 that I'd like to merge into this branch. Do you mind looking them over?

**Comment by derick-hess** [comment]
@nick-iris I think this is ready. Can you run it on the experiments at the dmc?

**Comment by nick-iris** [comment]
Yeah I'll do this now and let you know if there are any problems.

**Pull request merged**
