### PR TITLE
Revert "Add missing information to StationTXT output"

### PR DESCRIPTION
**Pull request by derick-hess**
Reverts PIC-IRIS/PH5#30

### CODE REVIEW

**Comment by derick-hess** [comment]
We still need to add the info below before merging:
- [ ] Azimuth
- [ ] Scale
- [ ] ScaleFreq
- [ ] ScaleUnits

**Comment by nick-iris** [comment]
@derick-hess I don't think we want to do this. Reverting the PR 30 will removed the other changes entirely once merged, but we still want those changes. Probably best to delete this PR.

You can just push straight to master after adding the remaining values. No big deal.

**Comment by derick-hess** [comment]
okay cool. I'll get azimuth and dip added this afternoon and push that

**Comment by nick-iris** [comment]
Sounds good. If you know how, you might as well add Scale and ScaleUnits while your at it.

 I added a comment explaining how the match up with PH5 in #13.

**Pull request closed without merging**
