### PR TITLE
extend time when there is overlap for ph5availability

### PR DESCRIPTION
**Pull request by damhuonglan**
### What does this PR do?
ph5api.py - get_availability():
+ help to extend time when there is overlap
+ fix bug with adjust len of time when extend
+ fix bug of identify gap (currently no output)
+ identify overlaps (currently no out put)
+ consider deploy and pickup time

### Relevant Issues?
#499 

### Checklist
- [ ] This PR is not directly related to an existing issue (which has no PR yet).
- [ ] All tests pass.
- [ ] Any new or changed features have are documented.
- [ ] Changes have been added to `CHANGELOG.txt` .
- [ ] First time contributors have added your name to `CONTRIBUTORS.txt` .

### CODE REVIEW

**Comment by hrotman-pic** [comment]
I have tested this PR with SmartSolo experiments and it looks like ph5availability output now covers all expected times.  For example, selected output from 21-002 station 8162:
ph5availability -n master.ph5 --station 8162 -S -a 2 -f t
9N 8162   -- GP1        1000.0 2020-11-07T22:42:00.009000Z 2020-11-08T01:00:00.001999Z
9N 8162   -- GP1        1000.0 2020-11-08T01:00:00.002000Z 2020-11-08T02:30:00.004999Z

I am in the process of testing other cases in PH5 experiments: Fairfield, Fairfield multiple deployment, RT130, Texan, and rolling Texan and need to finish those tests before I can write a review on this PR that is as correct and fully informed as possible.

**Review by hrotman-pic — APPROVED** [review]
This is working as expected, does not break anything, and is a big improvement to make ph5availability output consistent with data extraction.  Thank you for this.

Per discussion, this is an approving review to merge this PR.

**Comment by timronan** [comment]
This slows down the ph5 availability but is accurate. Because it is accurate, should be merged into Main. 

Without this update 30 minutes of data are missing:
```
ph5availability -n master.ph5 -p . -s 2022-04-18T00:00:00 -e 2022-04-18T00:30:00 --station 02118 -a 2

#n s      l  c   q                    earliest                      latest
4Q 02118  -- DP1   2022-04-18T00:00:00.000000Z 2022-04-18T00:00:00.096000Z
4Q 02118  -- DP2   2022-04-18T00:00:00.000000Z 2022-04-18T00:00:00.096000Z
4Q 02118  -- DPZ   2022-04-18T00:00:00.000000Z 2022-04-18T00:00:00.096000Z
```
With the update, all of the data are there:
```
time ph5availability -n master.ph5 -p . -s 2022-04-18T00:00:00 -e 2022-04-18T00:30:00 --station 02118 -a 2

#n s      l  c   q                    earliest                      latest
4Q 02118  -- DP1   2022-04-18T00:00:00.000000Z 2022-04-18T00:30:00.000000Z
4Q 02118  -- DP2   2022-04-18T00:00:00.000000Z 2022-04-18T00:30:00.000000Z
4Q 02118  -- DPZ   2022-04-18T00:00:00.000000Z 2022-04-18T00:30:00.000000Z

real    5m50.392s
user    5m46.883s
sys     0m2.765s
```

**Review by timronan — APPROVED** [review]
This branch is working as expected. Thanks for making these updates

**Pull request merged**
