### PR TITLE
Add ph5utils.py module.

### PR DESCRIPTION
**Pull request by nick-iris**
I've moved common code from the ph5tomsAPI.py, ph5tostationxml.py, and ph5toexml.py modules into a new module called ph5utils.py. The goal is to avoid having multiple versions of the same code.

@derick-hess you may wish to also go through these modules and see if there are other places where code can be shared.

**The following methods have been added/improved:**
- New utility method datestring_to_datetime added and includes more valid date formats
https://github.com/PIC-IRIS/PH5/blob/master/kitchen/ph5tostationxml.py#L207-L219
was replaced by:
https://github.com/PIC-IRIS/PH5/blob/master/kitchen/ph5tostationxml.py#L207-L219
using
https://github.com/PIC-IRIS/PH5/blob/ph5utils/kitchen/ph5utils.py#L92-L116
- Replaced calls to does_experiment_pattern_exists with calls to does_pattern_exists 
- Added better command line error handling to ph5tostationxml.py:
https://github.com/PIC-IRIS/PH5/blob/ph5utils/kitchen/ph5tostationxml.py#L657-L670

### CODE REVIEW

**Comment by derick-hess** [comment]
Great start on this. I think it's going to be really useful. I'll go through and see if there is more functionality that can be moved to this

**Comment by nick-iris** [comment]
I'll wait for you to check on where more functionality can be added. Feel free to merge once you're finished.

**Comment by nick-iris** [comment]
@derick-hess We were previously reading the Array and Das tables even for experiments that don't match the network requested.

Now the code only reads the Array and Das tables if the experiment network matches the requested network.

**Comment by derick-hess** [comment]
Thanks for catching that

**Comment by nick-iris** [comment]
@derick-hess  I have also added multi-processing to ph5toexml.py. I think we should merge this pull request now if you don't object.

I'm going to look into what performance difference there is (if any) when using threads versus multiple processes. It may be better to use threads.

**Comment by derick-hess** [comment]
I'm fine with merging now. I'm still catching up on laptops and metadata stuff for other projects and haven't gotten back to PH5 yet. I should be done with all that stuff today and back to PH5 on monday.

**Comment by derick-hess** [comment]
Threads will spawn faster than processes in most cases. That would be the main advantage I see. The shared memory space of threads isn't something we care much about in this case but the faster spawn time could make a difference.

**Pull request merged**
