### PR TITLE
Add setup.py script for setuptools

### PR DESCRIPTION
**Pull request by nick-iris**
@rsdeazevedo I've started the setup.py build script. Hopefully this will provide you with a good starting point.

It appears that the biggest challenge is going to be handling various library dependencies. You will notice that calling `python setup.py build` will successfully build the project, but `python setup.py install` will fail due to missing dependencies.

### CODE REVIEW

**Comment by nick-iris** [comment]
In an effort to move forward with the refactor branch I've improved the build process. The tests now pass since the absolute imports were fixed.

The following changes were made.
- Updated absolute imports to reflect new file structure
- Anaconda is now the suggested installation method for dependencies.
- Updated the [README.md](https://github.com/PIC-IRIS/PH5/blob/master/README.md) to include installation instructions.

@rsdeazevedo and @derick-hess  could you try installing PH5 using the installation instructions I wrote in the README?

Once you have the package installed we will want to test each utility to make sure it runs okay. I think some of the packages will still break due to uninstalled _C_ dependencies. 

With the ph5 virtual environment sourced you can run any module by just typing its file name. (e.g. to run ph5tomsAPI.py you just type "ph5tomsAPI.py" in any directory on the command line). I plan to change the setup.py configuration to create executables for these files instead so that you don't have to source the virtual environment. Once this is done, we'll want to remove the _apps_ executables that you currently use/maintain.

**Comment by nick-iris** [comment]
The updated README.md file can be found here: https://github.com/PIC-IRIS/PH5/blob/setuptools_build/README.md

**Comment by nick-iris** [comment]
@rsdeazevedo cs2cs.py is currently listed under /ph5/utilities/ but it doesn't appear to be a command line utility. I think it would be more appropriate under /ph5/core/. Would you agree?

**Comment by nick-iris** [comment]
@rsdeazevedo What are all the lines that call 
`sys.path.append (os.path.join (os.environ['KX'], 'apps/pn4'))`
used for? 

We should remove these if possible otherwise users will have to set environment variables during the installation process.  The scripts break without it. The setuptools.py module will create executables automatically for all the command line scripts, so there is no need to maintain the custom executables you have in the apps directory. I'm guessing that the KX environment variable is related to that?

**Comment by derick-hess** [comment]
THanks Nick I'll test things out today.

**Comment by nick-iris** [comment]
Good news! I now have setuptools configured to automatically create executables for the ph5 utilities and clients. After installing the PH5 project the user just needs to type the name of the module to run in order to execute it. (e.g. to run `ph5tostationxml.py` the user just types `ph5tostationxml` anywhere on the command line).

A few changes were required to get this working.

- All code in the `if __name == '__main__'` code block was moved into a separate function called main(). `if __name == '__main__'` now just calls the _main_ method.
    - This was necessary to define entry_points in setup.py so for automatic executable creation.
- Modules with dashes in their file names were changed to underscores. Setuptools would throw an error for modules containing dashes. The command line executables still contain dashes however, so there is no change there.  The following files where renamed:
  - initialize-ph5.py -> initialize_ph5.py
  - kml-builder.py -> kml_builder.py
  - meta-data-gen.py -> meta_data_gen.py
  - nuke-table.py -> nuke_table.py
  - sort-key-gen.py -> sort_kef_gen.py
  - sort-recv-kef.py -> sort_recv_kef.py
  - sort-shot-kef.py -> sort_shot_kef.py
  - time-kef-gen.py -> time_kef_gen.py

The following still needs to be done:
- [ ] Remove all references to `os.environ['KX']`
- [ ] Permanently remove executable scripts found in the apps/ directories
- [ ] Test each script for issues.

After those I think we're good to wipe out the master branch and install PH5 in this manor on the servers.

**Comment by nick-iris** [comment]
I ran each utility without any options. The following programs had problems, but the rest ran without error. I think most of the issues should be pretty easy to resolve.
- **novenGUI**
- **ph5toevt** - missing c dependency "firfilt_py"
- **ph5torec** - missing c dependency "firfilt_py"
- **125a2ph5** - missing c dependency "rt_125a_py"
- **1302ph5** - missing c dependency "rt_130_py"
- **dumpfair** - "KX" environment variable missing error
- **index_offset_t**
- **initialize-ph5** - "KX" environment variable missing error
- **pformaCL** - The external program xterm required. Not found.
- **ph5_merge_helper** - /bin/sh: table2kef: command not found
- **segd2ph5** - missing c dependency "bcd_py"
- **segy2ph5** - missing c dependency "ibm2ieee_py"
- **set_n_i_response** - Runtime error - (possible bug in code)
- **sort-recv-kef** - Runtime error - List index out of range (possible bug in code)
- **sort-shot-kef** - Runtime error - List index out of range (possible bug in code)
- **unsimpleton** - "KX" environment variable missing error

**Comment by rsdeazevedo** [comment]
The problem with novenGUI, and also ph5viewer, is that they can't find their configuration files. I'll have a fix for noven and let Lan know about ph5viewer.

**Comment by nick-iris** [comment]
ph5viewer works fine on my machine

**Comment by nick-iris** [comment]
You'll probably have to fix all the ones that deal with the missing "KX" environment variable. I believe that there is no need for this environment variable anymore since setuptools creates & manages the executables.

**Comment by rsdeazevedo** [comment]
It does not absolutely need its config file to operate so if it can't 
read the config file it just uses the default configuration silently, i 
think. I'll ask Lan.

**Comment by rsdeazevedo** [comment]
I looked at most of those and the ones i looked at were just using the 
KX environment so it could be used as a stand alone script for 
debugging. On those i'll comment out where it is setting sys.path based 
on KX.

**Comment by nick-iris** [comment]
I removed most of the places where the KX environment was referenced on the top of the module, but there were some that were more intwined with the rest of the code.

The files that still have issues are marked here: https://github.com/PIC-IRIS/PH5/pull/72#issuecomment-315168342

 Ones that are checked have been addressed.

**Comment by nick-iris** [comment]
@rsdeazevedo If you can fix the remaining scripts that we should be able to have this merged before Wednesdays working group call.

**Comment by derick-hess** [comment]
I'll work on fixing some of those this afternoon.

**Comment by derick-hess** [comment]
Looks like sort-shot-kef can be deleted. It doesn't work anymore with version 4 of PH5 anyway

**Comment by nick-iris** [comment]
Do you want me to permanently delete the following using `git-filter-branch`? They are no longer needed.
-  _install.py_
- _ph5/utilities/apps/_
- _ph5/utilities/sort_shot_kef.py_
- _ph5/core/app.sh_
- _ph5/core/apps/_
- _ph5/clients/apps/_

Also can _ph5/utilities/sort_recv_key.py_ be removed?

**Comment by derick-hess** [comment]
Yeah that's fine. sort-recv-kef and sort-shot-kef can be removed.

**Comment by nick-iris** [comment]
Okay I'll do that now. Just to give you a heads up, once I rewrite the history you'll want to create a new fresh clone of the project.

**Comment by nick-iris** [comment]
After rewriting the history and force pushing this PR was automatically closed. I'll create a new PR where I reference this one.

**Comment by nick-iris** [comment]
Damn that screwed things up since now all the historys are completely different. What do you want to do? 

I think it is safe to wipe out the refactor branch with this one if you guys are happy with the way the setuptools install works.

**Comment by derick-hess** [comment]
I think that will probably be fine as long as all the changes in the refactor branch are also in setuptools_build. If not I still have those changes saved on my machine and can recommit them after the change.

I haven't tested the setuptools install yet but was goign to do that over the weekend on a fresh linux vm and a fresh mac build to see exactly what we might be missing and what isnt in anaconda.

**Comment by nick-iris** [comment]
Okay thanks. Sorry I didn't think it would do that, although in hindsight it does make sense.

The only change missing from the _setuptools_build_ branch is the following commit on the _refactor_ branch: https://github.com/PIC-IRIS/PH5/commit/cbd2b37e7d3cc913840efcf330d969e986ab0651

I rebased the _refactor_ branch as of this commit: https://github.com/PIC-IRIS/PH5/commit/c5da8bdc6ef7b0a0b6906cce7d4bbae03ad1cd6e

**Comment by nick-iris** [comment]
As far as I can tell,  novenGUI and pformaCL are the only scripts still have issues. The novenGUI has a 'KX' envirionment variable problem and is missing its configuration file. The pformaCL code runs but is missing a necessary dependency called 'xterm'.

I'll probably work some over the weekend too, so email me if you have any trouble getting this running. It should be pretty straight forward once you have all the system dependencies installed.

**Comment by rsdeazevedo** [comment]
Also, ph5view apparently has problems with missing config files. Lan is 
working on it. The config files for noven will end up working in a 
similar way to the way Lan handles them in ph5view. I'll talk with her 
on Monday. Derick is going to have pformaCL check for xterm, notify the 
user, and exit gracefully if it is missing.

**Comment by nick-iris** [comment]
pformaCL already exits pretty gracefully. Here's what it outputs when I try to run the program.
```
(ph5) falco-6:PH5 nick$ pformaCL
The external program xterm required. Not found.
```
We'll probably just want to document the _xterm_ dependency. Is pformaCL a command line script for Windows?

**Comment by rsdeazevedo** [comment]
Its a command line version of pforma that uses a slightly different way 
of building a ph5 file from raw data in parallel and does not need qt. 
It has only been used on linux as far as i know but it may(?) work on 
Windows.

**Comment by nick-iris** [comment]
Oh I see _xterm_ is the windowing system for Unix. I saw "Window" and naively assumed Microsoft. I guess that's a sign that I should go home on a Friday.

**Comment by derick-hess** [comment]
xterm is also available on windows and mac so pformacl will work cross platform if the user wnats to install xterm. I'll add checks for it in pformaCL and inform the user that they can either run the regular pforma or download or install xterm

**Comment by nick-iris** [comment]
I was able to install PH5 as a dependent module for the PH5 Web Services and use it as an alternative to having local files. This vastly simplified the web services code and eliminated the need for me to manually copy the API code into web services after every change.

**Comment by derick-hess** [comment]
Nice. I htink I just pushed the last of the fixes as well. Noven now will check to see if you have config files installed in your home directory. If not it will ask you if you want to install them or just used the default configuration.

**Comment by nick-iris** [comment]
Great. Not a huge deal but I think there are still some references to environment variables that should eventually be removed or documented. I did a global search for _apps_ in the project, since these were removed, and it returned returned the following:

- ph5/core/
  - ibmfloat.py (2 matches)
    - 16: sys.path.append (os.path.join (os.environ['KITCHEN'], "apps", "pn2", "construct-2.0-
    2.4.zip")) 
    - 19: sys.path.append (os.path.join (os.environ['KITCHEN'], "apps", "pn2", "construct-2.00-
    py2.5.egg")) 
  - RT_130_h.py
    - 12: #sys.path.append (os.path.join (os.environ['KITCHEN'], "apps", "pn2", "construct-2.0-
    2.4.zip")) 
  - SEGY_h.py (3 matches)
    - 17: sys.path.append (os.path.join (os.environ['KITCHEN'], "apps", "pn2", "construct-2.0-2.4.zip")) 
    - 20: sys.path.append (os.path.join (os.environ['KITCHEN'], "apps", "pn2", "construct-2.00-py2.5.egg")) 
    - 25: #sys.path.append (os.path.join (os.environ['K3'], "apps", "pn3", "reconstruct-2.03dev-py2.6.egg")) 
- ph5/utilities/
  - dumpfair.py
    - 8: #sys.path.append (os.path.join (os.environ["KX"], "apps", "pn4")) 
  - kmz_builder.py (2 matches)
    - 1,129: # copy the icon files from $KITCHEN/apps/pn2/kmlicons/ 
    - 1,133: iconpath = kitchenpath+"/apps/pn3/kmlicons/" 
  - novenQC.py
    - 49: base = os.path.join (os.environ['KX'], 'apps/pn4/kmlicons') 
  - pformaIO.py
    - 755: sys.path.append (os.path.join (os.environ['K3'], "apps/pn3")) 
  - unsimpleton.py
    - 12: #sys.path.append (os.path.join (os.environ["KX"], "apps", "pn4"))

**Comment by derick-hess** [comment]
thanks i'll look through those and fix them

**Comment by derick-hess** [comment]
Fixing most of them now. kmz_builder can be removed though. It is no longer used.

**Comment by derick-hess** [comment]
Everything on the list should be fixed now. Almost all of it was actually just in comments that were never removed.

**Comment by nick-iris** [comment]
Okay should change this to the master branch? Both the beta and live web services are using this package of PH5.

**Comment by nick-iris** [comment]
We can then work on publishing to PyPi. There is an IRIS account we could use or you can create one for the PIC.

**Comment by derick-hess** [comment]
sounds good. I think we are ready to switch this to the master branch

**Comment by rsdeazevedo** [comment]
I just pushed the changes that Lan made to ph5view. Derick has reviewed 
this here and it's compatible to the way that noven keeps its config files.

**Comment by nick-iris** [comment]
Thanks for the fixes guys. Do you want me to replace the master branch or would you like to?

Whoever ends up doing it should probably also use `git-filter-branch` to permanently remove [ph5.utilities.kmz_builder](https://github.com/PIC-IRIS/PH5/blob/setuptools_build/ph5/utilities/kmz_builder.py) and the unneeded [ph5.clients.PH5View.ph5view](https://github.com/PIC-IRIS/PH5/blob/setuptools_build/ph5/clients/PH5View/ph5view) executable since it is a good time to do such a thing.

**Comment by derick-hess** [comment]
One thing I just came across when building on a completely fresh system. Until the new version of obspy comes out we need to include instructions for grabbing LLoyd's pull request from obspy and installing that, otherwise ph5tostationxml won't work. I think that is the only one that wont work with the current obspy version

**Comment by nick-iris** [comment]
Good call. I think these steps would be something like:

1. Open a terminal window
2. Run `git clone https://github.com/obspy/obspy.git` to clone ObsPy to your local machine.
3. Run `git checkout RESPtoInventoryResponse` to switch to the required developmental software branch.
4. Run `python setup.py install` in the root ObsPy project directory to install the required developmental version of ObsPy.

**Comment by derick-hess** [comment]
yeah I'll write down the steps. I'm doing it now on a fresh virtual machine

**Comment by derick-hess** [comment]
If you have time you can replace the master branch. I'll update the steps for obspy today then need ot start working on a more user friendly tool for loading RESP files into PH5

**Comment by nick-iris** [comment]
Okay I'll do that now before moving on to other things

**Comment by nick-iris** [comment]
I completely replaced master with the setuptools_build branch. I also re-added the required startapp() method to PH5ViewerwVispyAPI.py and permanently removed ph5.utilities.kmz_builder and the unneeded ph5.clients.PH5View.ph5view executable.

**Comment by nick-iris** [comment]
Everyone will need to re-clone their copy of the PH5 repo as the history was completely rewritten. If you don't it can cause some really messy merge conflicts in the future since the commit hashes won't match.

**Comment by nick-iris** [comment]
I think we can delete the remote _refactor_ and _setuptools_build_ branches now. I have them locally. What do you think?

**Comment by derick-hess** [comment]
I think it's safe to delete those branches. 

So far in my fresh linux vm testing I haven't found any issues with needed to install extra OS dependencies. They are all covered in Anaconda.  Took a bare virtual machine, installed only anaconda and ph5 then tried to create a PH5 archive from raw data with a tiny amount of data and everything worked. I'll still need ot do more extensive testing but so far Anaconda is looking good.

**Comment by nick-iris** [comment]
Okay that sounds good. In case you didn't know, you can create a developmental install of the project by running `pip install -e .` in the root project directory. This in turn runs `python setup.py develop`.

This is like installing but instead of copying to site-packages it adds a symbolic link (the .egg-link acts as a multiplatform symbolic link). With this setup as you make and save changes to the code they are reflected in the installed version.

**Pull request closed without merging**
