### PR TITLE
Fix broken install on CentOS and TravisCI

### PR DESCRIPTION
**Pull request by nick-iris**
### What does this PR do?
Changes the environment.yml file to fix a bug where PH5 wont install in certain environments.

### Relevant Issues?
#313 

### Checklist
- [ ] This PR is not directly related to an existing issue (which has no PR yet).
- [x] All tests pass.
- [ ] Any new or changed features have are documented.
- [ ] Changes have been added to `CHANGELOG.txt` .
- [ ] First time contributors have added your name to `CONTRIBUTORS.txt` .

### CODE REVIEW

**Comment by derick-hess** [comment]
I added a line to .travis.yml 
All these errors seem to come from the latest version of Conda. The conda team is trying to simplify the channels and combine them to speed up installations. Getting rid of the free channel has caused issues because the new base channel has many many less packages and versions of packages.

The line I added is also what obspy is doing right now as a temporary fix until this channel thing gtes worked out.

**Comment by dthomas1953** [comment]
Trying this build at home on a Mac Sierra 10.12.6.

I switched to this branch:
```
[dthomas@New-OS-Image-9 PH5]$ git status
On branch fix_build
Your branch is up-to-date with 'origin/fix_build'.

nothing to commit, working tree clean
```
and the environment.yml and .travis.yml files had the new changes.

But, when I executed:
**$ conda env update --name=ph5 -f=environment.yml**
I got this error:
```
[dthomas@New-OS-Image-9 PH5]$ conda env update --name=ph5 -f=environment.yml
Collecting package metadata (repodata.json): done
Solving environment: failed

ResolvePackageNotFound:
  - pyside -> qt=4.8
  - pyqt=4 -> qt=4.8
```

**Comment by dthomas1953** [comment]
When I executed
**conda config --set restore_free_channel true**
before the conda env update, it ran fine.
The installation wiki will have to be updated accordingly.

I'll try it on a Linux laptop on Monday.

**Comment by derick-hess** [comment]
I think we should get this change merged soon if everyone is in agreement this is a good solution for now. This way the CI is no longer broken and we can get some of the other pull requests merged as well

**Comment by dthomas1953** [comment]
I downloaded the fix_build branch, it compiles on a Linux Dell laptop, and tests came out.
I manually included the command "conda config --set restore_free_channel true" before updatng the environment.
Looks good to me.
----------------------------------------------------------------------
Ran 23 tests in 6.846s

OK

**Comment by dsentinel** [comment]
This fixes the install issues on my mac desktop. Merge away...

With the old and aging deps required for this project. I don't know if we will ever be able to get away from turning on the free channel.

I still have many Failures with runtests

**Pull request merged**
