### PR TITLE
Ph5toms change to make day volumes

### PR DESCRIPTION
**Pull request by damhuonglan**

### CODE REVIEW

**Comment by derick-hess** [comment]
@damhuonglan I'll give this a test for functionality. It currently fails the flake8 test, so it can't be merged until it passes flake8

**Comment by derick-hess** [comment]
@nick-iris I'm testing this on some data here at the PIC. So far it looks good. Can you also give it a test? Sometimes on nodes since samples don't start on even seconds it grabs a single sample from the previous day, but I think that is okay.

**Comment by damhuonglan** [comment]
For inday_breakup function, if the start_fepoch fall on the last day of a year, it will give the wrong result. I will fix it and update the 2 files so they meet flake 8.

**Comment by derick-hess** [comment]
@damhuonglan I removed the .DS_Store files you added to the branch. Make sure no extra files get added when commiting

**Comment by nick-iris** [comment]
Thanks Derick I'll look at it this afternoon. I'm curious if this update has any effect on the amount of memory consumed by of a ph5toms processes. Are we reading more data at a given time than before?  Is is possible to load less data at a given time into memory before writing it to miniSEED or SAC?

We are running into web service scalability issues here at the DMC and will want to try to reduce the memory overhead from each ph5toms process. I've observed that if there are 30 ph5toms processes running on a server it consumes ~10GB of memory (~300MB per process).

**Comment by derick-hess** [comment]
@nick-iris just started checking. On my system it uses 17MB just opening python and close to 100MB after imports

**Comment by nick-iris** [comment]
Hmm maybe there isn't much we can do unless we get rid of the ObsPy dependency for writing miniSEED and use a more streamlined approach as Chad suggested for performance.

**Comment by derick-hess** [comment]
It does look like I need to fix some things though. with the new das query mem usage keeps going up. I'll get a fix for that, as well as see if i can reduce some memory usage in other ways. I think using just the libmseed wrapper from obsy might be the way to go.

**Comment by derick-hess** [comment]
I'll try to get those changes in by monday afternoon to test

**Comment by nick-iris** [comment]
That sounds good to me. Thanks for the help.

**Pull request merged**
