### PR TITLE
ph5tomsAPI match FDSN web service start times

### PR DESCRIPTION
**Pull request by derick-hess**
Update to ph5tomsAPI to ensure the start times match the fdsn web services.

### CODE REVIEW

**Comment by nick-iris** [comment]
Thanks Derick. I'll deploy this change to the web services after lunch.

**Comment by derick-hess** [comment]
let me know when it is deployed and I'll run tests on everything. I ran tests comparing the fdsn web services compared to our local PH5 archive (which matches the DMC PH5 archive). I'll run the same tests on web service vs web service to make sure everything is good. 

The test grabs 10 seconds of data from every station and checks to make sure the start times match and that the data matches sample for sample.

**Comment by nick-iris** [comment]
I just deployed your changes to both the ph5wsbeta and ph5ws endpoints.

Note that the endpoints have been changed from ph5 and ph5beta to ph5ws and ph5wsbeta, as to match the other services.

**Comment by derick-hess** [comment]
Just ran the test on web service vs web service. No differences found. Start times matched as well as a sample by sample match check.

**Comment by nick-iris** [comment]
Great! Is the PIC data-group still working on the PH5 Wavefields Data? 

It sounds like once that is done, we are ready to have someone else at the DMC look at the data again.

**Comment by derick-hess** [comment]
The metadata for wavefields is updated now but I haven't done a thorough check on it. I will do that today. The RESP that is already in the mseed archive at the DMC was checked and is correct so I updated the RESP file  in the PH5 archive to match the one in the mseed archive. I also fixed the orientation in PH5.

I'll do a check of the metadata today and let you know. I think it will be ready for the DMC to check out tomorrow.

**Comment by nick-iris** [comment]
Hey Derick. Should this be merged? It is already deployed on the web services.

**Comment by derick-hess** [comment]
Yeah we can merge it.

**Pull request merged**
