### PR TITLE
Fix #298. ph5api cut sometimes returns too many samples

### LINKED ISSUE #298: [BUG] ph5api cut sometimes returns too many samples
**Describe the bug**
I came across an odd bug when querying YW (Wavefields) station 1001 channel DPZ.

The first odd behavior is that there appears to be 3 "duplicate" das entries for this channel in the experiment. This results in the data being returned 3 times when a request for this channel is made.

The second issue is that in certain cases more samples are returned than what was requested. 

For example, run the following request:

```
ph5toms -n master.ph5 -p /hdf5-data2/PH5_Experiments/pn4/16-015/ --station=1001 --channel=DPZ --starttime=2016-06-26T00:00:00 --stoptime=2016-06-26T00:00:01
```

Looking at this file with ObsPy we see that there are duplicate samples and in one case the program is cutting too much data.
```
>>> import obspy
>>> st = obspy.read("YW.1001..DPZ.2016-06-26T00.00.00.ms")
>>> print st
3 Trace(s) in Stream:
YW.1001..DPZ | 2016-06-26T00:00:00.000000Z - 2016-06-26T00:00:00.996000Z | 250.0 Hz, 250 samples
YW.1001..DPZ | 2016-06-25T23:43:57.832000Z - 2016-06-25T23:43:58.828000Z | 250.0 Hz, 250 samples
YW.1001..DPZ | 2016-06-25T23:43:57.832000Z - 2016-06-26T00:00:00.996000Z | 250.0 Hz, 240792 samples
```

**Environment (please complete the following information):**
 - Program Version [ph5toms 2019.93, ph5api 2019.93]

**Expected behavior**
For the example request in the bug description, I'd expect to see only one trace in the stream containing 250 samples of data.

### PR DESCRIPTION
**Pull request by nick-iris**
### What does this PR do?

This PR fixes bug #298. There was an issue with the scope of the `start_fepoch` variable in the ph5api cut method that was causing too much data to be cut in certain cases.

### Relevant Issues?

For more information see #298 

### Checklist
- [x] This PR is not directly related to an existing issue (which has no PR yet).
- [ ] All tests pass.
- [x] Any new or changed features have are documented.
- [x] Changes have been added to `CHANGELOG.txt` .
- [x] First time contributors have added your name to `CONTRIBUTORS.txt` .

### CODE REVIEW

**Comment by nick-iris** [comment]
Rebased [current master](https://github.com/PIC-IRIS/PH5/commit/44b31c41c24daae53cc01a046559c4138d7fe4a2) and force pushed.

**Comment by nick-iris** [comment]
The test for the ph5api cut method is now failing, but I'm wondering if this was even correct to begin with? As I demonstrated, the cut method definitely wasn't working correctly in certain cases.

**Comment by nick-iris** [comment]
Here is the failing test:
```
======================================================================
FAIL: test_cut (ph5.core.tests.test_ph5api.TestPH5API)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/travis/build/PIC-IRIS/PH5/ph5/core/tests/test_ph5api.py", line 875, in test_cut
    traces[6].start_time.epoch(fepoch=True))
AssertionError: 1550850123.0 != 1550849943.0
```

Were these timestamp values just taken from the what the cut method was currently producing or were they carefully pre-calculated?

**Comment by nick-iris** [comment]
I force pushed a new potential fix once I found some problems with the other, and tests are back to passing.

```
ph5toms -n master.ph5 -p /hdf5-data2/PH5_Experiments/pn4/16-015/ --station=1001 --channel=DPZ --starttime=2016-06-26T00:00:00 --stoptime=2016-06-26T00:00:01

| => msi -tg YW.1001..DPZ.2016-06-26T00.00.00.ms 
   Source                Start sample             End sample        Gap  Hz  Samples
YW_1001__DPZ      2016,177,23:43:57.832000 2016,177,23:43:58.828000  ==  250 250
YW_1001__DPZ      2016,177,23:43:57.832000 2016,177,23:43:58.828000 -0.996 250 250
YW_1001__DPZ      2016,178,00:00:00.000000 2016,178,00:00:00.996000 961.2 250 250
Total: 1 trace(s) with 3 segment(s)
```

**Comment by nick-iris** [comment]
I've added a fix to #286 to this PR as well. PH5 now cuts to the closest sample falling on or after the requested start time. @derick-hess Do you have time to test this?

**Comment by derick-hess** [comment]
@nick-iris Yeha I should be able to to test this late this afternoon

**Pull request merged**
