### PR TITLE
Timing correction issues

### PR DESCRIPTION
**Pull request by rsdeazevedo**
Changes made to ph5API to fix a bug in timing and to better present clock performance information.
geod2kef was re-factored to use ph5API and correctly calculate sign of offsets along the array.
time-kef-gen re-factored to use ph5API and to correctly calculate clock drift for texans with large time offsets.
ph5toevt and ph5torec make use of latest changes to ph5API.

### CODE REVIEW

**Comment by nick-iris** [comment]
Hey Steve,

You are trying to merge something based on the old file structure into the refactor branch which is causing over 1000 unintended file conflicts.

I think it would be best to make a new branch from the _refactor_ branch, and then add all of your updated files to a new commit on that branch. Then you should be able to merge automatically.

-Nick

**Comment by rsdeazevedo** [comment]
Nick;

That is what i thought i was doing.

steve.

**Comment by nick-iris** [comment]
No worries, it's not a big deal at all. I suggest using [SourceTree](https://www.sourcetreeapp.com/) for git operations. It will make you life a lot easier.

From the command line, all you need to do is the following:
1. `git checkout refactor`
2. `git pull`
3. `git branch [[your new branch name]]`
4. `git checkout [[you new branch name]]`
5. ` git add [[file to commit]]` // you have to do this for each file you want to include in the commit
6. `git commit -m [[your commit message describing your changes]]`
7. ` git push`

In GitHub can then make a new pull request from your new branch into the _refactor_ branch.

**Comment by nick-iris** [comment]
Note that it will probably be easiest to copy the files you changed into your new branch based on _refactor_ and then add them to the commit.

**Comment by rsdeazevedo** [comment]
That is what i meant to do. I had a 'cook book' of steps that Derick 
e-mailed me but i must have not checked out the refactor branch before i 
checked out the refactor_2017.191 branch and did the adds and commits? 
Who ever gave command names in git the same names as in svn (but totally 
with different effects) is an evil trickster.>:o

**Comment by nick-iris** [comment]
I would definitely try out  [SourceTree](https://www.sourcetreeapp.com/) . If nothing else, it gives you a really nice visualization of what the remote and local branches look like so you can tell what is going on.

**Pull request closed without merging**
