### PR TITLE
Ph5 validate

### PR DESCRIPTION
**Pull request by CeliaPacheco**
Added error and warning checks to ph5validate

### CODE REVIEW

**Comment by nick-iris** [comment]
Looks good. Another good check might be to raise a warning if a permanent FDSN network code is entered, as this should rarely if ever be the case for experiments PH5.

**Comment by derick-hess** [comment]
Good idea. We can just grab the list of permanent networks in csv from from http://www.fdsn.org/networks/?permanent=1&type=csv 

Have ph5_validate try to grab the latest from online but we can also have a csv file to use as backup if the machine isn't online.

**Comment by nick-iris** [comment]
Temporary networks always start with a number (0-9) or X,Y,Z so you just need to check the first character.

For example:
```
    def is_permanent(network):
        if not network[0].isdigit() and \
           self.network[0] != "X" and \
           self.network[0] != "Y" and \
           self.network[0] != "Z":
            return True  # permanent network code
        else:
            return False  # temporary network code
```

**Comment by chad-iris** [comment]
> Temporary networks always start with a number (0-9) or X,Y,Z so you just need to check the first character.

Keep in mind that this rule will likely be removed in the future.  The current discussion on network codes is that they will be up to 8 characters, allowing them to be globally unique and then the above rule is no longer needed.

**Comment by derick-hess** [comment]
Thanks Chad. We'll keep that in mind.

**Pull request merged**
