### PR TITLE
Newhelp

### PR DESCRIPTION
**Pull request by dthomas1953**
Thank your for contributing to PH5

Before submitting a PR, please review the pull request guidelines:
https://github.com/PIC-IRIS/PH5/blob/master/CONTRIBUTING.md#submitting-a-pull-request

### What does this PR do?
Publish the new help feature, where $ ph5 shows a list of subprograms, $ ph5 --all shows the complete list. Additionally, the new entry_points module is used by setup.py.

### Relevant Issues?
Resolved.

### Checklist
- [x] This PR is not directly related to an existing issue (which has no PR yet).
- [x] All tests pass.
- [x] Any new or changed features have are documented.
- [x] Changes have been added to `CHANGELOG.txt` .
- [x] First time contributors have added your name to `CONTRIBUTORS.txt` .

### CODE REVIEW

**Comment by nick-iris** [comment]
I rebased master and force pushed since the unit test were failing. @dthomas1953 You'll need to reset your local head to the the new commit. You can do this by running the following git commands:

`git checkout newhelp`
`git reset --hard 32041dcec0f4c0f8f22ccf6b69b8fefef5b5688a` (this should be the hash of whatever the latest commit is)

It looks like the unit tests are still failing. I think this is because of some issues creating the test dataset. I'lll look into it some more.

**Comment by nick-iris** [comment]
@dthomas1953 You can go ahead and merge this if you are satisfied

**Comment by dthomas1953** [comment]
I pulled, fixed the two discrepancies. While I was expecting changed only to setup.py and entry_points.py,. git added many other files (after I had run python setup.py install). I went ahead and re-committed/pushed. Can you check it out, @nick-iris ? 
I tried running $ python runtests and $python runtests.py --include_ph5_dependent, and got scads of errors. Should you be in ph5 to run that?

**Comment by nick-iris** [comment]
Yes you need to run the test from the root ph5 project directory. Like I said, since I rebased and forced pushed you needed to reset you local head. You shouldn't have had to push 10 commits.

**Comment by dthomas1953** [comment]
@nick-iris before I merge, should I do the 
```
git checkout newhelp
git reset --hard e969837a191c4e343d965376afc86d931ae34248
``` commands to get caught up? 

Also, still getting errors on runtests. Running from the same directory as entry_points.py, clients/, etc. Should I be in a ph5 folder with actual data and a master.ph5 file?
```
======================================================================
ERROR: test_print_report (ph5.clients.tests.test_ph5availability.TestPH5Availability)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/dthomas/ph5/PH5/ph5/clients/tests/test_ph5availability.py", line 84, in setUp
    nickname='master.ph5')
  File "/Users/dthomas/ph5/PH5/ph5/core/ph5api.py", line 221, in __init__
    os.path.join(path, nickname)))
APIError: (0, 'PH5 file does not exist: ph5/test_data/ph5/master.ph5')

----------------------------------------------------------------------
Ran 23 tests in 0.004s

FAILED (errors=23)
```

**Comment by nick-iris** [comment]
What is your current working directory? You shouldn't have to make any local changes besides resetting your head. Everything was ready to go.

**Comment by dthomas1953** [comment]
```
(ph5) spike:ph5 dthomas$ pwd
/Users/dthomas/ph5/PH5/ph5
(ph5) spike:ph5 dthomas$ ls
CONTRIBUTORS.txt	__init__.py		__pycache__		core			entry_points.pyc	test_data
LICENSE.txt		__init__.pyc		clients			entry_points.py		help.py			utilities
(ph5) spike:ph5 dthomas$
```

**Comment by nick-iris** [comment]
You need to be up a directory in /Users/dthomas/ph5/PH5/

**Comment by dthomas1953** [comment]
I just want to revert to the one before all the un-necessary changes.
Should I execute
```
git checkout newhelp
git reset --hard e969837a191c4e343d965376afc86d931ae34248
```

**Comment by nick-iris** [comment]
Let me force push again to fix the issue

**Comment by dthomas1953** [comment]
@nick-iris :
```
You need to be up a directory in /Users/dthomas/ph5/PH5/
```
That was this first place I tried it, still all errors.

```
python runtests.py
. . .

----------------------------------------------------------------------
Ran 23 tests in 0.004s

FAILED (errors=23)

**Comment by dthomas1953** [comment]
I will stand by.

**Comment by nick-iris** [comment]
Okay in your /Users/dthomas/ph5/PH5/ directory run

```
git checkout newhelp
git reset --hard e969837a191c4e343d965376afc86d931ae34248
```

**Comment by dthomas1953** [comment]
DId it.

**Comment by nick-iris** [comment]
Something odd on my end. Tests seem to be passing fine in TravisCI but are now failing on my local machine.

**Comment by nick-iris** [comment]
How many test failures are you seeing locally? I'm seeing failures with the ph5availability tests.

**Comment by dthomas1953** [comment]
Yes, they're all ph5availability.
```
OK
test_analyze_args (ph5.clients.tests.test_ph5availability.TestPH5Availability) ... ERROR
test_convert_time (ph5.clients.tests.test_ph5availability.TestPH5Availability) ... ERROR
test_get_args (ph5.clients.tests.test_ph5availability.TestPH5Availability) ... ERROR
test_get_array_order_id (ph5.clients.tests.test_ph5availability.TestPH5Availability) ... ERROR
test_get_availability (ph5.clients.tests.test_ph5availability.TestPH5Availability) ... ERROR
test_get_availability_extent (ph5.clients.tests.test_ph5availability.TestPH5Availability) ... ERROR
test_get_availability_percentage (ph5.clients.tests.test_ph5availability.TestPH5Availability) ... ERROR
test_get_channel (ph5.clients.tests.test_ph5availability.TestPH5Availability) ... ERROR
test_get_end (ph5.clients.tests.test_ph5availability.TestPH5Availability) ... ERROR
test_get_geoCSV_report (ph5.clients.tests.test_ph5availability.TestPH5Availability) ... ERROR
test_get_json_report (ph5.clients.tests.test_ph5availability.TestPH5Availability) ... ERROR
test_get_report (ph5.clients.tests.test_ph5availability.TestPH5Availability) ... ERROR
test_get_sampleNos_gapOverlap (ph5.clients.tests.test_ph5availability.TestPH5Availability) ... ERROR
test_get_sample_rate (ph5.clients.tests.test_ph5availability.TestPH5Availability) ... ERROR
test_get_slc (ph5.clients.tests.test_ph5availability.TestPH5Availability) ... ERROR
test_get_slc_info (ph5.clients.tests.test_ph5availability.TestPH5Availability) ... ERROR
test_get_start (ph5.clients.tests.test_ph5availability.TestPH5Availability) ... ERROR
test_get_sync_report (ph5.clients.tests.test_ph5availability.TestPH5Availability) ... ERROR
test_get_text_report (ph5.clients.tests.test_ph5availability.TestPH5Availability) ... ERROR
test_get_time_das_t (ph5.clients.tests.test_ph5availability.TestPH5Availability) ... ERROR
test_has_data (ph5.clients.tests.test_ph5availability.TestPH5Availability) ... ERROR
test_main (ph5.clients.tests.test_ph5availability.TestPH5Availability) ... ERROR
test_print_report (ph5.clients.tests.test_ph5availability.TestPH5Availability) ... ERROR

Ran 23 tests in 0.006s

FAILED (errors=23)
```

**Comment by nick-iris** [comment]
I did just did a fresh clone of the project and everything worked fine. Try deleting your local copy of PH5 and then recloning the project.

**Comment by dthomas1953** [comment]
Will do. Have to go to class soon, will do a fresh start in the morning.

**Comment by nick-iris** [comment]
Sorry for the inconvenience, I'm not sure what exactly caused the issue.  Let me know if you get your tests working, and then I'll merge this PR. After you get a fresh clone of the project you'll need to run:

```
git checkout newhelp
./create_ph5.sh
python runtests.py
```

**Comment by dthomas1953** [comment]
Sounds good, thanks for the help.

**Comment by dthomas1953** [comment]
I re-cloned, checked out newhelp, and ran create_ph5 and runtests.py.

Worked a whole lot better this time:
```
----------------------------------------------------------------------
Ran 23 tests in 14.112s

OK
Closing remaining open files:ph5/test_data/ph5/master.ph5...doneph5/test_data/ph5/master.ph5...doneph5/test_data/ph5/master.ph5...done
```

**Comment by nick-iris** [comment]
Great glad that did the trick. Let's merge it.

**Comment by nick-iris** [comment]
@dthomas1953 Next time please do a squash merge. Helps to keep the history cleaner.

**Comment by dthomas1953** [comment]
How do I invoke a squash merge?

**Comment by nick-iris** [comment]
In GitHub there is a drop down that allows you to select the "Squash and Merge" option.

**Comment by dthomas1953** [comment]
OK, will endeavor to remember that next time.

**Comment by nick-iris** [comment]
Thanks. The only reason is a we don't want a whole bunch of incremental commits in the master branch. Ideally it should just contain single commits from each pull request that gets merged.

**Comment by dthomas1953** [comment]
Okay, thanks

**Pull request merged**
